### ISSUE TITLE
ES: 1203.json COSE seems to be invalid

### ISSUE THREAD

**Issue by jeroentrappers** [eu-digital-green-certificates/dgc-testdata#104]
https://raw.githubusercontent.com/eu-digital-green-certificates/dgc-testdata/main/ES/2DCode/raw/1203.json

When decoding the COSE input of this file, the payload decodes as a BigInt, not a byte array. Also in cbor.me it seems the encoding is different from "normal" files.

Anyone else having issue with this file?

**Comment by Santivicen** [comment]
Hi we have check that test, and has previous errors that We have solved. I think we have a problem with the pull request. We remove that test and we are checking what happen with that test
