### ISSUE TITLE
CY files use Base64 encoding for test input.

### ISSUE THREAD

**Issue by jeroentrappers** [eu-digital-green-certificates/dgc-testdata#105]
@lexin10 

https://github.com/eu-digital-green-certificates/dgc-testdata/blob/14741a336586772bba4b4e7b18c2170e62be02fb/CY/2DCode/raw/1.json#L27

This file uses Base64 encoding for the input test data, it should use HEX encoding, as all the other files.

**Comment by psavva** [comment]
@lexin10 Please can you have a look at this one.

**Comment by JChrist** [comment]
Also, all CY test files have a `VALIDATIONCLOCK` set **before** the contained certificate `iat` field, causing all validations to fail

**Comment by lexin10** [comment]
Thank you @JChrist for letting us know this issue.
@JChrist I would appreciate if we can have a small session to see how are you testing these flows? 
So like that the cyprus team will be able to identify and fix futures issues.

**Comment by JChrist** [comment]
@lexin10 sure, the Greek team is always eager to help :)
Feel free to send me an e-mail at jchrist[at]cytech.gr to set it up

**Comment by lexin10** [comment]
> @lexin10
> 
> https://github.com/eu-digital-green-certificates/dgc-testdata/blob/14741a336586772bba4b4e7b18c2170e62be02fb/CY/2DCode/raw/1.json#L27
> 
> This file uses Base64 encoding for the input test data, it should use HEX encoding, as all the other files.

This has been fixed
