### ISSUE TITLE
Exp is actually valid for expected invalid cert

### ISSUE THREAD

**Issue by yspreen** [eu-digital-green-certificates/dgc-testdata#106]
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/14741a336586772bba4b4e7b18c2170e62be02fb/common/2DCode/raw/CO17.json

The exp value is 5/5, while the clock is 5/3. This is valid, thus the test fails.

**Comment by yspreen** [comment]
Pinging @nodh

**Comment by yspreen** [comment]
Same for CO16

**Comment by JChrist** [comment]
Adding here my own confusion, seeking clarifications.
For CO16, the expected error is INVALID: validation clock before "ISSUED AT". So the expected error is not about exp, but about iat.
However, the validation clock is at the exact second of `iat` field: 2021-05-03T18:00:00Z
Is this supposed to fail? Verifiers MUST NOT accept certificates issued at the exact second of `iat` (like that is possible, but anyway)?
If that is the case, then `DGC3.json` (at least) MUST also fail, suffering from the same issue.

**Comment by yspreen** [comment]
Good point. IAT validation is not part of the Swift tests (yet).

Since all entries in the hcert actually have a date of issuance in the payload, it seems redundant and not really needed. But we can add it nonetheless

**Comment by nodh** [comment]
The intention for `CO16.json` was to set the `VALIDATIONCLOCK` to some date in 2021, and the `ISSUED_AT` in the CWT (inside the COSE) to some date in 2023. Apparently, the resulting test file did not capture this, so I'll update that. Thanks for spotting the error!
