### ISSUE TITLE
FR: unable to decode certificate

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#128]
@adelourme and @SchulzeStTSI, Please have a look and advise.

References: 
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/FR/2DCode/raw/recovery_ok.json 
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/FR/2DCode/raw/test_pcr_ok.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/FR/2DCode/raw/vaccin_ok.json

We were unable to decode this certificate. It may be corrupt or in an incorrect format.

-----BEGIN CERTIFICATE-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuJjL6t8WfFqkcvLv4AxbhNzACWmue8REZKeXwI4kJgiR2gXb/K0bZhpT0/f6rQiDI/B/pI7OXc5zogfHw3vVU9/goMMH8MDvmEwd4fF4ifZ/8JFkyxwllJ8Y6gHr5cjYGmMIfjR5CbVFkThi5Svqm3iX0ree9dGfgER2sVlk26KOcpzLfASjtVMfdkB21lUHXIWvJ30nWaQ/0mgciSjZjG5cLRh8IO0PudJJI2ZvXEpF52UYBOyWukylMEIDtF9JEIb2QQd6EVwx2WHAjPrhRAJDV8zi28eN1uZPeq+psi0lqBHLpeM7xIRqNOC77AVbfxoddddvegskwwLpgzD2UVi1Wtw0xZ6UK9Jknxi2xWadJogCnKqo+BST4zCpI9p7lkJxL34MGakWNOBge/kLkRnTUpcGrKg5UWR89wHYhhgROWON2Rz5orsEz4mCwTp93+zYchdPG0qM9AH5vAO82Ync/xuwkJP58yzeNjW6FBjs8TK7tB5y22kq5HGFVst/Hf/h9/mRoFWFQCYOfmJYU6I2GgOzqNlrGK651e5e6lCZw3TTBTwiQ9usW1h4FwbyxSfbyQAncSn5spJw3wZKfo523TS3kOgePzK+csmJgYANpiDvmR75OFrbI3BOgCG6XgZr+mFdBonKZ2n+WhLqpWAI+h4z5Xc/TOEfZ078n50CAwEAAQ==
-----END CERTIFICATE-----

**Comment by lab-incert** [comment]
I got the same issue as commented here: https://github.com/eu-digital-green-certificates/dgc-testdata/commit/be2d4b189cab110150b72b8b410fbf41339d5924#commitcomment-50962272

**Comment by adelourme** [comment]
We changed certificate value in last commit

**Comment by bhavin-qryptal** [comment]
@adelourme 

There are few more issues to resolved. Please refer to https://github.com/eu-digital-green-certificates/dgc-testdata/pull/135

Thank you.
