### ISSUE TITLE
HR: COSE Payload is missing expiry date

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#129]
@TKlauenberg 
@daniel-eder
@kristinaleko 

FYI and kind attention.

[HR/2DCode/raw/1.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/cce3001e358418ea2fe02f8fc1dba110916be4ae/HR/2DCode/raw/1.json)
and
[HR/2DCode/raw/3.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/cce3001e358418ea2fe02f8fc1dba110916be4ae/HR/2DCode/raw/3.json)

COSE Payload is missing mandatory expiry date: Key 4.

**Comment by SchulzeStTSI** [comment]
@kristinaleko any update on this?

**Comment by kristinaleko** [comment]
@SchulzeStTSI @bhavin-qryptal  the test files have been updated yesterday , it should be resolved now.

**Comment by daniel-eder** [comment]
@kristinaleko thanks you - the automated check for HR passes, so I'll close this issue.
