### ISSUE TITLE
PL: validation_clock time is after dgc_expiry_date value

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#130]
References:
[PL/2DCode/raw/1.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/cce3001e358418ea2fe02f8fc1dba110916be4ae/PL/2DCode/raw/1.json)
[PL/2DCode/raw/2.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/cce3001e358418ea2fe02f8fc1dba110916be4ae/PL/2DCode/raw/2.json)

@js-pcsi, FYI and review please.

validation_clock time is after dgc_expiry_date value. This would make DGC invalid at validation_clock.

**Comment by bhavin-qryptal** [comment]
Hi @gregsons 

Reference: https://github.com/eu-digital-green-certificates/dgc-testdata#readme

EXPECTEDEXPIRATIONCHECK: Data from input is valid when verifying at the moment defined in TESTCTX.VALIDATIONCLOCK

In my understanding this means that, Certificate should be valid if it was to be validated @ VALIDATIONCLOCK time. With that logic, DGC Expiry date should NOT be after VALIDATIONCLOCK time.

@SchulzeStTSI, Please confirm or comment futher.

**Comment by SchulzeStTSI** [comment]
@gregsons The validationclock provides the timestamp where the "scan" is executed. It must be formated in json date time format : 2021-05-16T20:34:51.085231Z (it seems that the most also accept timestamps with offsets)

If you validate the certificate, the dgc expiry should not be after the validationclock time.

**Comment by SchulzeStTSI** [comment]
@gregsons @bhavin-qryptal I've correct it.

**Comment by bhavin-qryptal** [comment]
Thank you @SchulzeStTSI . Please comment when code changes is merged.

**Comment by SchulzeStTSI** [comment]
@bhavin-qryptal To make it conrecte, i check 2.json of PL and they have the following values: 

Validation Clock: 2021-05-18T12:22:51.032763Z 
 Exp:   Tuesday, 18. May 2021 11:11:07

So from my perspective the Certificate is arround 1 hour expired. @gregsons will provide a fix for the clocks.
