### ISSUE TITLE
FR: Validation issues in Test PCR sample

### ISSUE THREAD

**Issue by lab-incert** [eu-digital-green-certificates/dgc-testdata#131]
From this sample:
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/FR/2DCode/raw/test_pcr_ok.json

RAT Test name and manufacturer "3D Medicines" is not known the https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/main/valuesets/test-manf.json

Date/Time of Sample Collection (sc) & Date/Time of Test Result (dr) should be provided as string (date-time format) rather than int timestamp as we can see in json schema: https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/main/DGC.combined-schema.json

```json
...
"sc": {
  "description": "Date/Time of Sample Collection",
  "type": "string",
  "format": "date-time"
},
"dr": {
  "description": "Date/Time of Test Result",
  "type": "string",
  "format": "date-time"
}
...
```

**Comment by bhavin-qryptal** [comment]
![image](https://user-images.githubusercontent.com/84303320/118800659-c0124d80-b8d2-11eb-9389-925b10aef5f0.png)

**Comment by adelourme** [comment]
Thanks, I just created a pull request to correct that

**Comment by bhavin-qryptal** [comment]
@adelourme and @SchulzeStTSI , A couple of more issue still needs to be fixed. Comments @ https://github.com/eu-digital-green-certificates/dgc-testdata/pull/135 

Would you like re-open this OR create a new issue?
