### ISSUE TITLE
Ambitious test scenarios may be contra productive

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#14]
Guys, after a night of producing test-files to be supplied I really need to say this.... You are trying too hard. 

Let us ask ourselves: What is the purpose with interoperability tests?

It is that country X can read, parse, and validate a QR-code produced by country Y. Nothing else.

So. Apart from that you have to jump directly into your code and extract the different types of encodings during the production of a QR-code, the intermediate tests are hard to perform (due to possible different CBOR/JSON encodings).

Since we are short of time my suggestion is that every country supply:
- A QR-code
- The JSON-payload (optional)
- The data expressed as TESTCTX and EXPECTEDRESULTS

Each and every step between the reading of the QR-code and the result (SUCCESS/ERROR) should be left for internal testing.

**Comment by asitplus-pteufl** [comment]
I would say there are more perspectives here, yes the interoperability tests, like you describe them, are one part. then there is the creation side, where not too much test cases are required, but then there is the validator side. 

for the validation side there is definitely a need to have a good basic test set that covers all the edge cases (e.g. no qr code of the interop tests might be signed with RSA, or none of the qr codes might have the KID in the protected header). such a test set is probably going to have 40-50 test cases, which then can be checked by any validator app automatically with unit testing (and probably also the country-specific codes). also, it's not only about the valid cases, these test cases also ensure that a code is marked as invalid by a validation app when it is invalid (this would not be covered all by the interop tests with other countries alone).

Regarding the intermediate tests and the stored CBOR/ZLIB encodings, well on the creation side this will lead to different results, but for most of these steps this is not the case for the validation apps. if you unzip the package you would need to have the same COSE/CBOR structure. If you need/can do this in every step is another question, but I think putting the data in the test cases is a minimal effort and having it for e.g. detailed analysis if a test case fails is for sure helpful.

the expected errors help to validate the correct error detection of the validation app (it would not help if the signature is broken but the validation app fails at reading BASE45). In Austria we also plan to map the errors to certain catagories, which will then give a simple information to the validator (e.g. certificate is fine, but expired, or certificate format cannot be read), so we need to make sure that the app throws the right error.

so, I think having those test cases for the validation apps is really necessary if we want to make sure that the validation apps in europe behave in the same way for the global properties/rules (country-specific rules are of course another issue not addressed by those test sets).

**Comment by martin-lindstrom** [comment]
Fine. I hear you :-)

But breaking up a QR-code in its parts doesn't give us more useful tests. Someone still has to provide a QR-code signed with RSA, or a KID in the unprotected header (you meant  **un**protected, right?).

But be aware that comparing encodings may not work. See https://github.com/eu-digital-green-certificates/dgc-testdata/issues/11.

**Comment by asitplus-pteufl** [comment]
@martin-lindstrom we are in the process of doing this (based on the google docs I shared) here (they will be checked in here later)
https://github.com/ehn-digital-green-development/hcert-kotlin/tree/feature/testgen/src/test/resources

and we will describe those initial examples in a table that tsystems has created yesterday.
i meant unprotected (whatever the less likely scenario is :-)

my impression is that we will encounter issues during the creation of these test sets (and also due to your input and those of others) and some adaptions will be made.

**Comment by martin-lindstrom** [comment]
I’ll make sure to supply some odd corner cases :-)

**Comment by SchulzeStTSI** [comment]
Please add your tests here to the list: 

https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/BasicDgcTestsList.md

(Link please the related JSON)
