### ISSUE TITLE
Right to write

### ISSUE THREAD

**Issue by jtomasuzis** [eu-digital-green-certificates/dgc-testdata#143]
Hello, 
I need to upload test data for the Czech Republic, I do not have the right to create a directory and upload data, can you help me?

Thank you

Jakub Tomas

**Comment by martin-lindstrom** [comment]
Make a fork of the repo, and then a pull request.

**Comment by daniel-eder** [comment]
@jtomasuzis Write access has been granted, however the workflow is similar: Create a branch, push it to origin (github) and then create a pull request. One of the team members or member state developers will review it and we'll merge it
