### ISSUE TITLE
NL: EXPECTEDKEYUSAGE

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#146]
**Affected Country**: NL

## Issue Description

Very high number of test files are failing EXPECTEDKEYUSAGE test. 
e.g. Test DGC Signed with a cert tagged with extended Key Usage 1.3.6.1.4.1.0.1847.2021.1.2 for Vacination Issuers. (Reference: https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/certificate-governance.md )

Refer to https://github.com/bhavin-qryptal/dgc-testdata/runs/2629576617?check_suite_focus=true for detailed report with such failures.

## Proposed Solution

Appropriately tagged certificates should be used to sign DGCs.

**Comment by bhavin-qryptal** [comment]
> Currently is defined that one DGC can have 1 Event from only one type. The definition for the business rules is still in progress.
Reference: https://github.com/eu-digital-green-certificates/dgc-testdata/issues/161

There are large number of test files from NL which does not comply with this rule e.g. https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/NL/2DCode/raw/310.json . Please help fix this as well.

**Comment by wasperen** [comment]
fixed by PR #254
