### ISSUE TITLE
BE: Schema issue

### ISSUE THREAD

**Issue by taseo** [eu-digital-green-certificates/dgc-testdata#150]
**Affected Country**: BE
## Issue Description

`sc` and `dr` when decoded from `3.json` test case are not string as expected according to the [schema](https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/main/DGC.combined-schema.json)

```
{
  t: [
    {
      ci: '01BEBRE1RAWW42HIFL1TYZQFKWMQ#N',
      co: 'BE',
      dr: 2021 - 05 - 17T13: 25: 00.000Z,
      is: 'SC-BE',
      sc: 2021 - 05 - 17T08: 25: 00.000Z,
      tc: '87260309',
      tg: '840539006',
      tr: '260415000',
      tt: 'LP6464-4'
    }
  ],
  dob: '2001-02-12',
  nam: { fn: 'Ebraert', gn: 'Peter', fnt: 'EBRAERT', gnt: 'PETER' },
  ver: '1.0.0'
}
```

**Comment by bhavin-qryptal** [comment]
@taseo @daniel-eder This could be closed, as test is running successfully against latest file with a minor change I have committed.
