### ISSUE TITLE
PT: Schema Issues

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#151]
**Affected Country**: PT

## Issue Description
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/PT/2DCode/raw/1.json - Presence of empty 'r' and 't' nodes in JSON.
![image](https://user-images.githubusercontent.com/84303320/119014560-abb17c00-b9ca-11eb-997d-4b6b58cb7683.png)

https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/PT/2DCode/raw/2.json - Presence of empty 'v' and 't' nodes in JSON.

https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/PT/2DCode/raw/3.json - Presence of empty 'v' and 'r' nodes in JSON and incorrect date format for 'dr' and 'sc'
![image](https://user-images.githubusercontent.com/84303320/119014884-fc28d980-b9ca-11eb-9eeb-83dd1b72a09f.png)

https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/PT/2DCode/raw/4.json - Similar to above 

## Proposed Solution

COSE payload should comply with schema expectaions.
COSE, CBOR and JSON data should be in sync.

**Comment by SchulzeStTSI** [comment]
@bhavin-qryptal Are the schema issues still shown in the validation script?

**Comment by bhavin-qryptal** [comment]
> @bhavin-qryptal Are the schema issues still shown in the validation script?

I believe yes. Unless some recent change by anyone else.

**Comment by pjsramos** [comment]
This issue was solved in last update

**Comment by bhavin-qryptal** [comment]
Thank you @pjsramos . @daniel-eder ,  I have updated the known issue list.
