### ISSUE TITLE
IS: DSC Certificate Issues

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#152]
**Affected Country**: IS

## Issue Description

https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/IS/2DCode/raw/1.json
Ref: https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/certificate-governance.md 
extendedKeyUsage 1.3.6.1.4.1.0.1847.2021.1.1 is for Test Issuers, but it is used for Vaccination Cert.

https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/IS/2DCode/raw/4.json
This test is expecting EXPECTEDKEYUSAGE test to fail. However, this DGC is signed with DSC having empty ExtendedKeyUsage, which makes this DSC valid to sign all types of DGC. (Reference: https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v1_en.pdf - Section A.4 Extended key Usage Identifiers)

## Proposed Solution

Appropriate type of signing certificates with correct key usage should be used.

**Comment by gunnarif** [comment]
@bhavin-qryptal  
Hi! It should be fixed now with the latest pull request.

**Comment by daniel-eder** [comment]
Verified in https://github.com/eu-digital-green-certificates/dgc-testdata/actions/runs/878692667
