### ISSUE TITLE
IT: DSC Certificate Issues

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#153]
**Affected Country**: IT

## Issue Description

Reference: https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/certificate-governance.md#43document-signer-dsc

DSC Certificate Algorithm is RSA_WITH_SHA256 but Key is of type EllipticCurvePublicNumbers.

Refer:
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/IT/2DCode/raw/1.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/IT/2DCode/raw/2.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/IT/2DCode/raw/3.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/IT/2DCode/raw/4.json

## Proposed Solution

DSC Certificate with Algorithm RSA_WITH_SHA256 should use Key of type RSAPublicKey.
and
DSC Certificate with Algorithm ECDSA_WITH_SHA256 should use Key of type EllipticCurvePublicNumbers.

**Comment by martin-lindstrom** [comment]
See my comment in https://github.com/eu-digital-green-certificates/dgc-testdata/issues/155
