### ISSUE TITLE
Test Data Issue - Invalid Certificate Algorithm

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#154]
## Issue Description

Test Data Issue - Invalid Certificate Algorithm

Ref: https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/common/2DCode/raw/CO28.json

DSC Certificate is having unsupported Certificate Signature Algorithm: <ObjectIdentifier(oid=1.2.840.10045.4.3.4, name=ecdsa-with-SHA512)>.

## Proposed Solution

Valid values are RSA_WITH_SHA256 and ECDSA_WITH_SHA256

**Comment by martin-lindstrom** [comment]
No. It's not an error. The spec that you refer to states the following about the hash function:

SHA-2 with an output length ≥ 256 Bit
And the SHA-2 family consists of SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224, SHA-512/256.

**Comment by bhavin-qryptal** [comment]
> No. It's not an error. The spec that you refer to states the following about the hash function:
> 
> SHA-2 with an output length ≥ 256 Bit
> And the SHA-2 family consists of SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224, SHA-512/256.

Pleaser refer to my response @ https://github.com/eu-digital-green-certificates/dgc-testdata/issues/157

**Comment by bhavin-qryptal** [comment]
Thank you for clarifying. I would close this as per https://github.com/eu-digital-green-certificates/dgc-testdata/issues/155
