### ISSUE TITLE
RO: DSC Certificate Issues

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#155]
**Affected Country**: RO

## Issue Description

Reference: https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/certificate-governance.md#43document-signer-dsc

DSC Certificate Algorithm is RSA_WITH_SHA256 but Key is of type EllipticCurvePublicNumbers.

Refer:
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/RO/2DCode/raw/1.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/RO/2DCode/raw/2.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/RO/2DCode/raw/3.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/RO/2DCode/raw/4.json

## Proposed Solution

DSC Certificate with Algorithm RSA_WITH_SHA256 should use Key of type RSAPublicKey.
and
DSC Certificate with Algorithm ECDSA_WITH_SHA256 should use Key of type EllipticCurvePublicNumbers.

**Comment by martin-lindstrom** [comment]
So. What's wrong with this? Exactly where in the referred document does it say that the CA must use a signature algorithm that corresponds with the public key in the signed certificate?

**Comment by bhavin-qryptal** [comment]
> So. What's wrong with this? Exactly where in the referred document does it say that the CA must use a signature algorithm that corresponds with the public key in the signed certificate?

Certificate Signature Algorithm is used to identify associated Public Key type. Why would you have Certificate Signature Algorithm ECDSA_WITH_SHA256 with Public Key type RSAPublicKey and vis-a-versa?

**Comment by martin-lindstrom** [comment]
No. You are wrong.

It's perfectly legal for a CA to use RSA to sign all types of certificates.

**Comment by bhavin-qryptal** [comment]
Thank you for clarifying, I have studied this more and realized that I got it wrong, I had wrong understanding before. I would close all these tickets.
