### ISSUE TITLE
SE: DSC Certificate Issues

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#157]
**Affected Country**: SE

## Issue Description

Reference: https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/certificate-governance.md#43document-signer-dsc

https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/SE/2DCode/raw/1.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/SE/2DCode/raw/2.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/SE/2DCode/raw/4.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/SE/2DCode/raw/5.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/SE/2DCode/raw/6.json

DSC Certificate is having Unsupported Signature Algorithm: <ObjectIdentifier(oid=1.2.840.10045.4.3.4, name=ecdsa-with-SHA512)>.

## Proposed Solution

DSC Certificate with Algorithm RSA_WITH_SHA256 should use Key of type RSAPublicKey.
and
DSC Certificate with Algorithm ECDSA_WITH_SHA256 should use Key of type EllipticCurvePublicNumbers.

**Comment by martin-lindstrom** [comment]
No. It's not an error. The spec that you refer to states the following about hash function:

> SHA-2 with an output length ≥ 256 Bit

And the SHA-2 family consists of SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224, SHA-512/256.

**Comment by bhavin-qryptal** [comment]
> No. It's not an error. The spec that you refer to states the following about the hash function:
> 
> > SHA-2 with an output length ≥ 256 Bit
> 
> And the SHA-2 family consists of SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224, SHA-512/256.

Reference: https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v1_en.pdf  - Section 3.3.2 Signature Algorithm

![image](https://user-images.githubusercontent.com/84303320/119024536-c0474180-b9d5-11eb-8579-b7275a198b82.png)

According to this only ECDSA_WITH_SHA256  and RSA_WITH_SHA256  are supported.

**Comment by martin-lindstrom** [comment]
Yes. But this is related to the signatures of the green certificates. Not the document signing certificates.

**Comment by bhavin-qryptal** [comment]
Thank you for clarifying. I would close this as per https://github.com/eu-digital-green-certificates/dgc-testdata/issues/155
