### ISSUE TITLE
FR: DSC Certificate Issue

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#158]
**Affected Country**: FR

## Issue Description

Reference: https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/certificate-governance.md#43document-signer-dsc

DSC Certificate Algorithm is RSA_WITH_SHA256 but Key is of type EllipticCurvePublicNumbers.

Refer:
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/FR/2DCode/raw/recovery_ok.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/FR/2DCode/raw/vaccin_ok.json

## Proposed Solution

DSC Certificate with Algorithm RSA_WITH_SHA256 should use Key of type RSAPublicKey.
and
DSC Certificate with Algorithm ECDSA_WITH_SHA256 should use Key of type EllipticCurvePublicNumbers.

**Comment by martin-lindstrom** [comment]
See my comment in https://github.com/eu-digital-green-certificates/dgc-testdata/issues/155
