### ISSUE TITLE
Test Data Issue - Invalid KID

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#160]
## Issue Description

Test Data Issue - Invalid KID on DGC

Ref: https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/common/2DCode/raw/CO28.json

Invalid COSE kid value 

Expected :b'_t\x91\x01\x95\xc5\xce\xcb'
Actual   :b'\x19\x9d\x9c|\xc2\xf0\xc8\xaf'

## Proposed Solution

Use correct KID on COSE Payload.

**Comment by SchulzeStTSI** [comment]
@bhavin-qryptal This file is copied from the SE set. https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/SE/2DCode/raw/5.json

**Comment by martin-lindstrom** [comment]
@SchulzeStTSI The Swedish file was updated to have the correct kid.

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom Thank you very much. I'll update it.

**Comment by SchulzeStTSI** [comment]
Closed with https://github.com/eu-digital-green-certificates/dgc-testdata/commit/71d1360ac0cd094e2c03285b4ccbe00160bb1360
