### ISSUE TITLE
ES: Corrupt Test Data JSON Files

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#165]
**Affected Country**: ES

## Issue Description

Corrupt Test Data JSON Files. Most likely due to CERTIFICATE field spread across multiple lines.

@Santivicen , @daniel-eder 
Looks like due to recent pull request https://github.com/eu-digital-green-certificates/dgc-testdata/pull/156

Reference: 
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/ES/2DCode/raw/2001.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/ES/2DCode/raw/2002.json

## Proposed Solution

Remove new line characters from CERTIFICATE field might fix this.

**Comment by Santivicen** [comment]
Hi, we have remove that wrong test. There was a problem with pull request and old files where added on it. So sorry.

**Comment by daniel-eder** [comment]
Thank you, @Santivicen !

Closed in #200
