### ISSUE TITLE
ES: EXPECTEDEXPIRATIONCHECK

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#169]
**Affected Country**: ES

## Issue Description

EXPECTEDEXPIRATIONCHECK Failing. 

**dgc_issue_date** time is AFTER **validation_clock** time.

> E           assert datetime.datetime(2021, 5, 17, 14, 44, 47, 106000, tzinfo=datetime.timezone.utc) <= datetime.datetime(2021, 5, 17, 9, 11, 47, 777000, tzinfo=tzutc())

Ref:
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/ES/2DCode/raw/1101.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/ES/2DCode/raw/1103.json

## Proposed Solution

Reference: https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/README.md

EXPECTEDEXPIRATIONCHECK: Data from input is valid when verifying at the moment defined in TESTCTX.VALIDATIONCLOCK

DGC Issue date should be BEFORE Validation Clock and DGC Expiry Date should be after Validation Clock.

**Comment by Santivicen** [comment]
Hi, we find other errors on that test, and remove them. We are going to solve all the problems, like the one that you tell us here, thanks.

**Comment by bhavin-qryptal** [comment]
@SchulzeStTSI and @daniel-eder , This could be closed as latest tests for ES are good.

**Comment by bhavin-qryptal** [comment]
@daniel-eder , Please help re-open this. Test is failing for three files.

```
>           assert dgc_issue_date <= validation_clock
E           assert datetime.datetime(2021, 5, 24, 8, 18, 18, 680000, tzinfo=datetime.timezone.utc) <= datetime.datetime(2021, 5, 17, 9, 11, 47, 777000, tzinfo=tzutc())
```

**Comment by bhavin-qryptal** [comment]
Closing this ticket and test data is modified to exclude this test.
