### ISSUE TITLE
CZ: UTF-8 Encoding Issues and Invalid DSC Certificates

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#172]
**Affected Country**: CZ

## Issue Description

Reference: https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/CZ/2DCode/raw (5 scripts under this)

It seems that files are not using UTF-8 Encoding, and DSC Certificate provided is not a valid one.

![image](https://user-images.githubusercontent.com/84303320/119127529-04365700-ba67-11eb-926a-27724d71c6eb.png)
![image](https://user-images.githubusercontent.com/84303320/119127842-62fbd080-ba67-11eb-9020-96eb76381805.png)
Ref: https://report-uri.com/home/pem_decoder

## Proposed Solution

Help fix test file encoding and CERTIFICATE value.

**Comment by dslmeinte** [comment]
Also: the cases 1, 3, 4 seem to have BOMs?

**Comment by teiwacz** [comment]
Hi about certificate, data are just a public key not a cert. So this works:
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQLV3BtN60prQ7I1EG5gLwQGsirtP
CYl9fCo3/8pqrT/CJBuk8yrd9REuSSmvriCCTOfxjC2b5qrZhiJgNIc7ZQ==
-----END PUBLIC KEY-----

But I guess the expected content is certificate. 
We will fix that with encoding. Thx for feedback

**Comment by bhavin-qryptal** [comment]
@daniel-eder , This issue is not resolved. All the files are still having encoding issues. Please re-open and also revert known_issues.csv

**Comment by daniel-eder** [comment]
@bhavin-qryptal can you verify this again on latest main? While #230 did not fix it, it seems #234 did. 
This test is from after we merged #234 and removed the known issues: https://github.com/eu-digital-green-certificates/dgc-testdata/runs/2684757827 and it passed. The PR also had the issues in xpasses.

**Comment by bhavin-qryptal** [comment]
@daniel-eder , Yes indeed, you are correct. Please ignore my earlier comments.
