### ISSUE TITLE
SE: validationClockInstant in Testdata

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgc-testdata#173]
@martin-lindstrom is there a special reason for validationClockInstant? I saw thisin other country files  as well .

**Comment by martin-lindstrom** [comment]
@SchulzeStTSI Oops, it must be a mistake in the test generation code. I'll make sure to fix it.

And the reason that you see it in other countries testfiles are most likely that they have copied Swedens solution. I think that this is highly questionable, and only makes sense if the countries in question use the [dgc-java](https://github.com/DIGGSweden/dgc-java) library in the exact way as SE is (which I doubt).

**Comment by martin-lindstrom** [comment]
See PR https://github.com/eu-digital-green-certificates/dgc-testdata/pull/174

**Comment by martin-lindstrom** [comment]
@SchulzeStTSI You seem to have incorporated some sort of check at check-in that fails. https://github.com/eu-digital-green-certificates/dgc-testdata/actions/runs/863709420

Honestly. We need to keep this simple. Nowhere can I find what is failing. The python code that is checking stuff is NOT necessarily correct (which I have proven a couple of times).

**Comment by daniel-eder** [comment]
@martin-lindstrom the check is still a WIP - I'll remove it from PRs for now, as we have failing files already in the repo. Your checks all passed (a test report is available as workflow artifact), I'll merge the pr.
