### ISSUE TITLE
Clarify CBOR

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#18]
There is a bit of confusion about the CBOR-field. SE and RO has added the CBOR-encoding of the payload but BG has added the CBOR-encoding of the entire CWT.

Both are CBOR-encoded, so I blame the test instructions ;-)

> Extract the CBOR content and validate the CBOR content against the RAW CBOR content field.

Should be: Extract the CBOR-encoded DGC payload from the CWT and ...

Or something like this.

ping @stamo

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom My logic here was to extract CBOR content from COSE, hash it and compare the hash in the JSON with the extracted hash to see if everything was extracted right. Do you think this would be the right approach or do you have any concerns?

**Comment by martin-lindstrom** [comment]
First: Extract CBOR content from COSE. The Cose_Sign1 structure is also CBOR encoded. So we need to be more specific, for example, "Extract the DGC payload from the Cose_Sign1 object in its CBOR-encoding".

And since two payloads, whether they are in CBOR-encoding or JSON-format, may be identical regarding the actual contents, their encodings are not guaranteed to be (since ordering is not fixed). So you cannot use hashes.

In order to compare two objects in order to find out whether they are the same I suggested (and the PR was merged) that the verifier decodes both objects, the encodes them, and lastly compare the two resulting encodings.

**Comment by asitplus-pteufl** [comment]
@martin-lindstrom @SchulzeStTSI 
let me check if I got this right:

- we have the ambiguity right now on extracting the CBOR content. We (Austria) take the whole CWT (which is also CBOR), other only take the HCERT itself and drop the other CWT headers
- if this is the right view, I think we have two options: (1) clarify that either the CWT of HCERT is meant by "CBOR", (2) explicitly add a step in the test procedure that covers the CWT (so CBOR would refer to CWT and there would be two test steps that  validated the CWT and then HCERT. In any case, either we need to update some of the test cases.

@nodh what's your opinion on that?

**Comment by SchulzeStTSI** [comment]
@asitplus-pteufl @martin-lindstrom 

My understanding from "CBOR" was the CBOR encoded JSON. Maybe we should introduce a "CWT" section as seperate step to make the definition waterproof?

**Comment by martin-lindstrom** [comment]
I suggest that we just clarify what is meant by CBOR and get going with the tests. Time is running out ...

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom You are right, let's define the CBOR as your first suggestion: "CBOR: The CBOR-encoding of the Digital Green Certificate payload."
