### ISSUE TITLE
feat: Automated tests for PRs only on changed files and/or the the affected member state folder

### ISSUE THREAD

**Issue by daniel-eder** [eu-digital-green-certificates/dgc-testdata#191]
## Issue Description

Currently, automated tests run on the entire repository, making it hard(er) to identify if a specific PR introduces new errors. 

## Proposed Solution

Automated tests should run either:
- only on changed files (see e.g. https://github.com/marketplace/actions/get-all-changed-files )
- or on the country-folder(s) affected by the PR, which in turn can be derived from the affected files
  - I believe this to be less ideal for PRs, but as a separate run config that uses an input variable that specifies the folder to run on it might be useful to verify the state of an entire country at once.

@bhavin-qryptal I'm tagging you in case you are interested in tackling this and/or have some input on the issue

**Comment by bhavin-qryptal** [comment]
Thank you @daniel-eder for tagging me. Internally, we have been thinking about this issue as well. 

Today's change I have submitted is to handle the very same problem you have highlighted. Hope it helps going forward. 

**Details:**
1. Build would be GREEN as long as there ZERO unknown errors. Currently the build should turn GREEN and that means all the known issues are identified.
2. Going forward, if you could reject any new pull request if the build becomes RED, we would stop introducing new errors and governance becomes easier.
3. Also, if we encourage each contributing member to run this test in their local branch before requesting for a pull request, it will help them discover issues much more earlier and they would stop introducing new errors.
4. With this, over a period of time the list of errors in the main repo should go down substantially and eventually becomes ZERO. 
5. If the process outlined above is possible, we may find not much extra benefits to have additional logic for country specific segregation. Kindly opine.

**Alternate option:**
1. The current test script does support a couple of flags (country flag and filename flag), which enables country specific run OR test file specific run. 
2. It is a matter of configuring the CI pipeline to invoke the test script with appropriate country flags.
3. Are you looking to run this workflow on demand manually with country code as parameter OR invoking it on some particular event automatically? (As I understand, currently you are invoking tests manually. Is that correct?)

**Comment by bhavin-qryptal** [comment]
Just now I have submitted a pull request (https://github.com/eu-digital-green-certificates/dgc-testdata/pull/193 ), which would enable specifying a country code if anyone desires to run tests for a given country only. By default it would run tests for all countries including common folder using parameter value '*'.

**Comment by daniel-eder** [comment]
@bhavin-qryptal thanks again for the PR. I think the process with known issues that you set up is a workable way to consider the existing issues in the test data. I'll make a note to re-enable it on PRs - we'll just need to test first if our known issues are up to date (which I haven't gotten around to yet)

**Comment by daniel-eder** [comment]
Checked & re-enabled to run on PR in #194
I'll close this - might revisit automatically filling the -c flag based on affected folder in the future, but for now the known issues offer a good solution to show only *new* issues a contribution may introduce. Thank you!

**Comment by bhavin-qryptal** [comment]
> Checked & re-enabled to run on PR in #194

Verification on PR was passing wrong parameter to the test script. This is fixed in https://github.com/eu-digital-green-certificates/dgc-testdata/pull/197

@daniel-eder , Please help approve and merge Verification on PR was passing wrong parameter to the test script. This is fixed in https://github.com/eu-digital-green-certificates/dgc-testdata/pull/197
