### ISSUE TITLE
Use string for schema version in raw content

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#2]
The Raw contents is defined to be as below. I suggest that a string is used to represent the `SCHEMA` version instead of an integer. How do I represent version "1.0.1" using an int?

Also, the example is a bit misleading where the validation time is set as `"VALIDATIONCLOCK":"12-03-2021",`. If it is a time-stamp it should be in JSON date-time format.

```
{
   "JSON":**JSON OBJECT**, 
   "CBOR":**CBOR (hex encoded)**, 
   "COSE":**COSE (hex encoded)**,  
   "BASE45": **BASE45 Encoded COMP**, 
   "PREFIX": **BASE45 Encoded Compression with Prefix HC(x):**,  
   "TESTCTX":{
               "VERSION":**integer**
               "SCHEMA":**integer (USED SCHEMA)**, 
               "JWK":**JWK Object** ,
               "2DCODE":**BASE64 Encoded PNG**,
               "EXPECTEDDECODE":**boolean**,
               "EXPECTEDVERIFY":**boolean**,
               "VALIDATIONCLOCK":**Timestamp**
               "DESCRIPTION":**string**
             }
}
```

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom The idea was to reference the used schema as iterating number to the schema folder.  ("/schema/[Number].json) But yes you are right, it would be more clear to use the schema version of the hcert schema itself. What do you think, is "/schema/hcert/[semver].json" a better representation for the folder? Then we can use semver in the schema field instead of a integer value.

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom For the JSON Timestamp you would to propose "2017-05-15T15:12:59.152Z" as defined in ISO8601 right? (https://docs.jsonata.org/date-time-functions)

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom I've setup a pull request https://github.com/eu-digital-green-certificates/dgc-testdata/pull/4/files

**Comment by martin-lindstrom** [comment]
> @martin-lindstrom For the JSON Timestamp you would to propose "2017-05-15T15:12:59.152Z" as defined in ISO8601 right? (https://docs.jsonata.org/date-time-functions)

Yes
