### ISSUE TITLE
DE: GR: IS: IT: LU: LV: PL: PT: SI: SK: Please upload correct public keys to acceptance.

### ISSUE THREAD

**Issue by Mark-Selezenev** [eu-digital-green-certificates/dgc-testdata#210]
**Affected Country**: DE: GR: IS: IT: LU: LV: PL: PT: SI: SK: 

## Issue Description

Currently the uploaded certificates(Test data) do not validate against the public keys uploaded to the acceptance test environment. The public key is either fully missing or the wrong public key has been uploaded.

## Proposed Solution

Please upload correct publickeys.

**Comment by SchulzeStTSI** [comment]
Please mark as well all files with GATEWAY-ENV:["ACC"] in the Testcontext.

**Comment by alfo1995** [comment]
@Mark-Selezenev Italy has uploaded the correct DSC last week, you should be able to validate our QR Code.

**Comment by gunnarif** [comment]
IS: added the GATEWAY-ENV

**Comment by gunnarif** [comment]
@SchulzeStTSI  should this be closed?

**Comment by gregsons** [comment]
PL has correct DSC public keys uploaded to the DGCG's acc env.
If there are any validation issues with currently uploaded public keys, let us know please.
