### ISSUE TITLE
test script fails to parse tag(0) date strings correctly.

### ISSUE THREAD

**Issue by dirkx** [eu-digital-green-certificates/dgc-testdata#213]
## Issue Description

Test scripts appear to not deal correctly with a properly tagged (0) time string (https://datatracker.ietf.org/doc/html/rfc8949#section-3.4.1) according to RFC7049 (https://datatracker.ietf.org/doc/html/rfc7049#section-2.4) table 3 - "Value for Tags".

E.g. passing a QR with

        "XX":0(
            "2021-05-24T24:00:00.000008Z"
          ), 

where XX is sc, dr, etc seems to fail.

## Proposed Solution

Fix the test to be RFC 8949 compliant.  Specifically it is this comparison:

E             -      '2021-05-25T11:21:51.145008Z'),
E             +      datetime.datetime(2021, 5, 25, 11, 21, 51, 145008, tzinfo=datetime.timezone.utc)),

Where the failed needs to either not convert the latter string to a datetime or convert the first string to a date time. I guess the most pragmatic thing would be to add to the loads() function flags similar as to the dumps() functions for controlling datetime conversion explictly.

**Comment by SchulzeStTSI** [comment]
@bhavin-qryptal Can you please add the tag 0 support for date time values?

**Comment by bhavin-qryptal** [comment]
In hand.

**Comment by bhavin-qryptal** [comment]
@SchulzeStTSI and @daniel-eder , This could be verified and closed.
