### ISSUE TITLE
SI: Schema validation failed

### ISSUE THREAD

**Issue by daniel-eder** [eu-digital-green-certificates/dgc-testdata#220]
**Affected Country**: SI

## Issue Description

#216 fixed #77, but introduced schema validation issues in the json files 1-6 in the standardized family name field, see https://github.com/eu-digital-green-certificates/dgc-testdata/runs/2675618736?check_suite_focus=true

**Comment by daniel-eder** [comment]
@jozemlakar 1.0.0 of the json schema provides the following regex https://github.com/eu-digital-green-certificates/ehn-dgc-schema/blob/02bf437b1f2efe80982e3172a85a757e549b3c64/DGC.combined-schema.json#L95 

Note that this field is the standardized family name, for the original name you can use https://github.com/eu-digital-green-certificates/ehn-dgc-schema/blob/02bf437b1f2efe80982e3172a85a757e549b3c64/DGC.combined-schema.json#L86 

Hope that clears it up!

**Comment by jozemlakar** [comment]
Much clearer, will fix ASAP.

**Comment by jozemlakar** [comment]
Added PR #222

**Comment by daniel-eder** [comment]
Closed in #222
