### ISSUE TITLE
CY: usage of V1 version of X509 certificates

### ISSUE THREAD

**Issue by gregsons** [eu-digital-green-certificates/dgc-testdata#231]
**Affected Country**: CY

## Issue Description

CY uses the **V1** version of X509 certificates.
Following dictionary states that it is meant to be V3 version:
https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/certificate-governance.md#13terminology

## Proposed Solution
Regenerate certificates to be V3 version.

@psavva - can you check it?
@SchulzeStTSI - could you confirm that certs SHALL be V3 version?

**Comment by psavva** [comment]
The DSC is created using the guidance as per the certificates guide:
https://github.com/eu-digital-green-certificates/dgc-participating-countries/blob/main/gateway/CertificatePreperation.md#dsc-conf

I would request that the guide is updated for X509v3 and we'll adapt to the changes as to generate the correct version.

The guide above generates X509v1

**Comment by psavva** [comment]
@SchulzeStTSI please can you confirm?

**Comment by psavva** [comment]
I have now confirmed the issue, and will upload a new DSC to retest using X509v3.
The new DSC will be uploaded and new Test will also be uploaded.

@lexin10 We can work on this on Monday morning

**Comment by psavva** [comment]
X503v3 DSC has been uploaded.
ALL Cyprus QR Codes will be deleted from this repository today, and new X509v3 Certificates will be used.
Once uploaded, I will close this issue.

**Comment by psavva** [comment]
https://github.com/eu-digital-green-certificates/dgc-testdata/pull/279

**Comment by psavva** [comment]
Please confirm and close this issue
