### ISSUE TITLE
Unable to fetch JSON Schema

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#239]
## Issue Description

Test Validation script is failing at it is unable to fetch schema from https://id.uvci.eu/DGC.schema.json which redirects to https://raw.githubusercontent.com/ehn-digital-green-development/ehn-dgc-schema/main/DGC.schema.json and give error 404.

## Proposed Solution

Ensure  https://id.uvci.eu/DGC.schema.json works. It should direct to https://raw.githubusercontent.com/eu-digital-green-certificates/ehn-dgc-schema/main/DGC.schema.json instead of https://raw.githubusercontent.com/ehn-digital-green-development/ehn-dgc-schema/main/DGC.schema.json

@daniel-eder , Could you help?

**Comment by daniel-eder** [comment]
Thanks for letting me know!
I can't immediately influence the redirect, but I've manually linked to our local fork of the schema, which will usually be updated when we received confirmation of a schema change (such as the recent renaming of the schema file)

**Comment by daniel-eder** [comment]
Updated the URL to `https://id.uvci.eu/DCC.schema.json`, it resolves correctly now
