### ISSUE TITLE
DE: LU: IS: Public keys do not pass validity check against CSCA. (Acceptance)

### ISSUE THREAD

**Issue by Mark-Selezenev** [eu-digital-green-certificates/dgc-testdata#242]
**Affected Country**: DE: LU: IS:

## Issue Description

Your public keys do not verify against CSCA so they are not trusted and although they are in the acceptance test, we can't accept them according to the reference materials. 

## Proposed Solution

I am not sure, technically we can drop the check but that will make the solution less secure. And if it was part of the reference materials then we should do it.

I thought about adding KIDS here but everyone should know their KID.

**Comment by Mark-Selezenev** [comment]
Perhaps when you uploaded the proper CSCA was there but then after somebody deleted the CSCA?

**Comment by gunnarif** [comment]
Hi!
Here is a code that can validate the IS DSC against the CSCA currently in the ACC
https://dotnetfiddle.net/zcpQWX

So I don't see any issue
Or is the validation failing for other reasons?

**Comment by Mark-Selezenev** [comment]
We tried the CSCA and DGC from acceptance with your code it works.

The reference code https://github.com/eu-digital-green-certificates/dgc-lib though does more and we are currently looking in to it. But it doesn't currently validate using the reference code.

**Comment by gregsons** [comment]
> 
> 
> We tried the CSCA and DGC from acceptance with your code it works.
> 
> The reference code https://github.com/eu-digital-green-certificates/dgc-lib though does more and we are currently looking in to it. But it doesn't currently validate using the reference code.

Concerning DE's DSC KID="f1sfUVIx8CA=".
We use the reference implementation of **dgc-lib** which doesn't validate/accept mentioned KID. In consequence that KID is not provided to the national backend and then to the validation app.

It seems that current implementation of dgc-lib doesn't accept the sub-CA structure of CSCA. 
CSCA:
- KID: "lkLenRso6HI="

![obraz](https://user-images.githubusercontent.com/82111466/120029839-eaf95180-bff6-11eb-94ef-0ccb6c545e2b.png)

- DSC: "f1sfUVIx8CA="

![obraz](https://user-images.githubusercontent.com/82111466/120029520-81794300-bff6-11eb-9da6-d29c580db02c.png)


@SchulzeStTSI 
@f11h 
@SZoerner

**Comment by thinkberg** [comment]
Can anyone explain what the exact problem is? It was accepted and it adheres to the rules in the trust framework.

**Comment by thinkberg** [comment]
We explicitly asked before. It looks like the library does not adhere to the rules (from the trust framework guidelines):

```
All  public  keys  and  certificates  marked  as  valid  in  the  EU  Public  KeyDirectory/Gatewayby Country A shall be trusted by Country B.If Country A has uploaded a public key certificate of a Certificate Authority (CA), all certificates issued by this CA shall be trusted by Country B.
```

In fact, this means that the trust anchor is the uploaded CSCA, nothing else.

**Comment by SchulzeStTSI** [comment]
When the DSC and the CSCA is visible by the /trustlist call of the gateway, then the CSCA and the DSC pass successfull the content checks of the gateway. Means the technical validation was possible and everything is fine with the certificates. The problem with the dgc lib seems like a bug in the lib. Therefore please provide the following information:

1. Try a Curl call on the /trustlist/DSC/DE. Is the DSC visible? If yes, the DSC was uploaded successfully
2. Please have a look in the dgc lib logs. Is there any exception? 
3. Which signature algorithm is used for the CSCA? RSASSA-PSS? ECDSA?
4. Check in the debug mode this line here: https://github.com/eu-digital-green-certificates/dgc-lib/blob/822affb7200a6b7f739a8fee3e59fdb72be6422c/src/main/java/eu/europa/ec/dgc/gateway/connector/DgcGatewayConnectorUtils.java#L46 is the lib able to come to this place for the certificates?

If you able to debug, please try to modify this line here: 

https://github.com/eu-digital-green-certificates/dgc-lib/blob/822affb7200a6b7f739a8fee3e59fdb72be6422c/src/main/java/eu/europa/ec/dgc/gateway/connector/DgcGatewayConnectorUtils.java#L46

to new JcaContentVerifierProviderBuilder().setProvider(new BouncyCastleProvider()).build(ca). 

@f11h

**Comment by asitplus-pteufl** [comment]
we can sucessfully validate all DE QR-codes, thus the DSC must have been correctly offered by the GW and accepted by our trust list.

**Comment by SchulzeStTSI** [comment]
@asitplus-pteufl You are using the current version of the dgc-lib as well right? On which java version/environment let you run it?

@Mark-Selezenev Which java version/environment are you using?

**Comment by gregsons** [comment]
@SchulzeStTSI FYI: PL env config:
`Java: alpine_3.11_openjdk11:1.1`
`CentOS Linux release 7.9.2009 (Core)`

**Comment by Mark-Selezenev** [comment]
I will clarify with the our guys when somebody answers.

Meanwhile may be this is somehow related to this: https://bugs.openjdk.java.net/browse/JDK-8146293%20targeted%20for%2011

**Comment by f11h** [comment]
Hello,
the problem is in dgc-lib gateway connector when trying to validate the CSCA issuance of a DSC. The problem only occurs when one of the certificates relies on a RSA-PSS PrivateKey.

I've just released a new version of dgc-lib which fixes this problem. I was now able to download and verify all 49 DSC from ACC environment with dgc-lib connector.

You can find the new version here: https://github.com/eu-digital-green-certificates/dgc-lib/releases/tag/0.4.5

**Comment by psavva** [comment]
I will go ahead and merge and test

**Comment by Mark-Selezenev** [comment]
We rebuilt the containers with the new library and re-deployed. Everything should be resolved, at least for EE.
