### ISSUE TITLE
CZ: invalid `iat` field

### ISSUE THREAD

**Issue by JChrist** [eu-digital-green-certificates/dgc-testdata#243]
**Affected Country**: CZ

## Issue Description
All json test data provided by CZ contain an `iat` that is later than the contained VALIDATIONCLOCK

## Proposed Solution
Please amend the test data to contain `iat` field earlier than the VALIDATIONCLOCK

**Comment by teiwacz** [comment]
Can you please clarify what iat stands for.  Thank you.

**Comment by JChrist** [comment]
The time when the certificate was created, as defined by the [spec here](https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md#336-issued-at)

**Comment by teiwacz** [comment]
Hello, can you recheck the issue. The pull should fix that. Thx

**Comment by SchulzeStTSI** [comment]
@JChrist Can we close the issue?

**Comment by JChrist** [comment]
I checked again with latest main branch (commit: 3b8e92998a7bd23418d53e9a24c4df54e3acc82d), however I still had failures for CZ `iat` field in 1.json and 3.json.
For 1.json:
Certificate is NOT issued YET! now:2021-05-31 14:11:37.501563Z iat:2021-05-31 17:11:38.000  

For 3.json:
Certificate is NOT issued YET! now:2021-05-31 14:04:23.803752Z iat:2021-05-31 17:04:24.000

**Comment by teiwacz** [comment]
Hello are you sure that when you are loading time that you are loading it as UTC not your local time as the diff between times are +3h (Greece local). Thanks for check.

**Comment by JChrist** [comment]
While it is printed as Greek local time, it is not loaded as such, since iat field is seconds since epoch

**Comment by teiwacz** [comment]
Ok, looks like it's problem with rounding secs in epoch, I will fix the validationclock time. Change will be available right after builds will work.
