### ISSUE TITLE
DE: Certificate Signing Algorithm / Size

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgc-testdata#252]
@SZoerner   Please check this with high urgency:

https://github.com/eu-digital-green-certificates/dgca-verifier-service/issues/42

I can see that one of your CSCA: 2.5.4.97 = NTRDE-HRB74346,CN = D-TRUST Root Test CA 2 2018,O = D-Trust GmbH,C = DE

is using the RSA-SSA-PSS Signature Algorithm, with a Key-Size of 4096.
I think this is causing the problem with validation of the CSCA against the DSC Certificate, which leads to the DSC to be unverifiable against the CSCA, and thus excluded in the Trust List in the Verifier Service.

**Comment by SchulzeStTSI** [comment]
@psavva There was a issue the last date which alreay solved that problem with a fix: https://github.com/eu-digital-green-certificates/dgc-testdata/issues/242

**Comment by psavva** [comment]
Closing this issue, Fix has been tested and verified working.
