### ISSUE TITLE
BE: Tagged CBOR Structs cannot be decoded

### ISSUE THREAD

**Issue by ubamrein** [eu-digital-green-certificates/dgc-testdata#263]
**BE**: 

## Issue Description

When using the fork of the [SwiftCBOR library](https://github.com/eu-digital-green-certificates/SwiftCBOR) and the data in this repository, we get the following error: 

> ▿ DecodingError
  ▿ dataCorrupted : Context
    ▿ codingPath : 3 elements
      ▿ 0 : AnyCodingKey(stringValue: "8", intValue: 8)
        - stringValue : "8"
        ▿ intValue : Optional<Int>
          - some : 8
      ▿ 1 : AnyCodingKey(stringValue: "1", intValue: 1)
        - stringValue : "1"
        ▿ intValue : Optional<Int>
          - some : 1
      ▿ 2 : _GenericIndexKey(stringValue: "Index 3", intValue: 3)
        - stringValue : "Index 3"
        ▿ intValue : Optional<Int>
          - some : 3
    - debugDescription : "Handling tags is not supported yet"
    - underlyingError : nil

Since this library is used in the [`ValidationCore`](https://github.com/ehn-digital-green-development/ValidationCore) and the [`dgca-app-core-ios`](https://github.com/eu-digital-green-certificates/dgca-app-core-ios) libraries, Apps using those two frameworks won't be able to decode tagged CBOR Data.

The `fatal error` can be traced back to the following [`fixme`](https://github.com/eu-digital-green-certificates/SwiftCBOR/blob/master/Sources/SwiftCBOR/Decoder/UnkeyedDecodingContainer.swift#L218)
 
## Proposed Solution

- Implement tagged content in `SwiftCBOR`?
- Disallow tagged content in `Hcert-Spec`

**Comment by SchulzeStTSI** [comment]
@ubamrein The structure of the BE codes looks good to me in the test data. Do you have any example what is not able to decode?

**Comment by SchulzeStTSI** [comment]
@ubamrein Please consider that the validation core swift had an update: 

https://github.com/ehn-digital-green-development/ValidationCore/blob/main/Sources/ValidationCore/Cose.swift#L56

as well the ios app core:

https://github.com/eu-digital-green-certificates/dgca-app-core-ios/blob/main/Sources/Services/CBOR.swift#L46

**Comment by ubamrein** [comment]
Thanks for the hint! The problem was actually in the pull strategy in the `Package.swift` File. We changed the repository URL without removing the version restriction.

Using the main branch directly seems to work for now (at least decoding :))
