### ISSUE TITLE
All validation tests are failing while attempting Schema validation

### ISSUE THREAD

**Issue by bhavin-qryptal** [eu-digital-green-certificates/dgc-testdata#280]
## Issue Description
All validation tests are failing while attempting Schema validation. Reason: https://id.uvci.eu/DCC.schema.json as well as https://id.uvci.eu/DGC.schema.json does NOT work.

@daniel-eder , Please help resolve.

**Comment by daniel-eder** [comment]
@bhavin-qryptal It seems someone changed the target of the id.uvci.eu URL redirects to an invalid github URL. These id.uvci.eu URLs are not under our direct control, I have to follow up to find out what happened here.

**Comment by daniel-eder** [comment]
Also see https://github.com/ehn-digital-green-development/ehn-dgc-schema/issues/94

**Comment by dirkx** [comment]
Stop gap in place (unversioned request go to main) -  lets discuss what is the right approach is with respect to using version numbers. And making sure test run against a (range) of specific versions in a controlled fashion.

**Comment by dirkx** [comment]
Stop gap updated on request of TSI to 1.0.1 - TSI plans to used versioned test post 1.2.X
