### ISSUE TITLE
FI: Missing Certificate in TESTCTX

### ISSUE THREAD

**Issue by vanlooverenkoen** [eu-digital-green-certificates/dgc-testdata#312]
**FI**

The pull requests should not be merged if unit tests are failing

## Issue Description

Certificate is missing from the follow files.: 
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/FI/2DCode/raw/1.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/FI/2DCode/raw/2.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/FI/2DCode/raw/3.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/FI/2DCode/raw/4.json
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/FI/2DCode/raw/4.json

## Proposed Solution

Certificate should be added to TESCTX to make sure we can validate the test data

**Comment by lari-kannisto** [comment]
Pull request #315: CERTIFICATE added to json files
