### ISSUE TITLE
LV: Providing "ma" attribute for NAAT examples

### ISSUE THREAD

**Issue by gregsons** [eu-digital-green-certificates/dgc-testdata#314]
**LV** 

## Issue Description

Concerning a QR code for a NAAT test from https://github.com/eu-digital-green-certificates/dgc-testdata/blob/1673a054d2dd874f508ffb0b2f539fdd3616ba56/LV/2DCode/raw/2.json:

```
{
   "ver":"1.0.0",
   "nam":{
      "fn":"Darbiņš",
      "fnt":"DARBINS",
      "gn":"Kalvis",
      "gnt":"KALVIS"
   },
   "dob":"1974-01-04",
   "t":[
      {
         "tg":"840539006",
         "tt":"LP6464-4",
         "nm":"1copy COVID-19 qPCR Kit",
         "ma":"1drop Inc",
         "sc":"2021-06-02T02:25:00Z",
         "dr":"2021-06-02T03:45:00Z",
         "tr":"260373001",
         "tc":"NVD",
         "co":"LV",
         "is":"Nacionālais veselības dienests",
         "ci":"urn:uvci:01:lv:39d9da8d15e39b93a68b3e095f4f56d9"
      }
   ]
}
```

The "ma" attribute is dedicated for RAT tests, so it shouldn't be provided in QR code for NAAT tests.

## Proposed Solution

Delete the "ma" attribute in NAATs' QR codes.

@ArtursMednis

**Comment by ArtursMednis** [comment]
This is corrected now.
