### ISSUE TITLE
EE: PLEASE try our new codes in the onboarding table and report the result.

### ISSUE THREAD

**Issue by Mark-Selezenev** [eu-digital-green-certificates/dgc-testdata#316]
## Issue Description

PLEASE try our new codes in the onboarding table and report the result. (Don't use the IOS version, because it crashes and the bug has been reported)

**Comment by DKvarn** [comment]
I have tested the QR-codes with our iOS verifier app and it works, the iOS version (SwiftCBOR) got a fix about two weeks ago https://github.com/eu-digital-green-certificates/SwiftCBOR/commit/9210abf60c16ab8be8e106cc126d6daa6931e2c0
 or are you referring to another bug?

**Comment by Mark-Selezenev** [comment]
Can you post that also here: https://github.com/eu-digital-green-certificates/dgca-app-core-ios/issues/56 @DKvarn

**Comment by Mark-Selezenev** [comment]
@DKvarn Also please mark with + + + in the onboarding table.

**Comment by DKvarn** [comment]
@Mark-Selezenev the fix are implemented in dgca-app-code-ios about 12 days ago so SwiftCBOR shouldnt be the problem

**Comment by gregsons** [comment]
Validation by PL at 2021-06-10 15:47 CEST
**VAC**: OK
**TEST**: OK (expired by PL rules)
**REC**: OK
