### ISSUE TITLE
ES: Broken test files

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#32]
Files 1201, 1202 and 1203 has wrapped JSON object within `"`. Should be a JSON-object
Files 2001 and 2002 has a `}` in the wrong place (after 2DCODE).

Please fix.

A question to @SchulzeStTSI: When you approve the PR, don't you check that the files are valid with some sort of tool?

**Comment by martin-lindstrom** [comment]
And the files 1201, 1202 and 1203 uses Base64 instead of hex-encoding.

**Comment by martin-lindstrom** [comment]
But SE successfully validated the other files :-)

**Comment by martin-lindstrom** [comment]
After the last update:

201, 202, 203 - Bad test files

501: nam.fnt: Illegal transliteration: FICTICIO ACTIVO

502: nam.fnt: Illegal transliteration: FICTICIO ACTIVO

503: nam.fnt: Illegal transliteration: FICTICIO ACTIVO

1201: v[0].vp: Value 'COVID-19 Vaccine Moderna' is not allowed according to the 'sct-vaccines-covid-19' value-set

1201: v[0]: dn is larger than sd. This doesn't make sense

2001: t: Empty array in 't' - not allowed, 

2001: r : Empty array in 'r' - not allowed

2002: v: Empty array in 'v' - not allowed, t=Empty array in 't' - not allowed

**Comment by Santivicen** [comment]
So sorry, I forget to put a comment here. We remove that invalid test.

**Comment by jeroentrappers** [comment]
#104 also related to the ES files.

**Comment by bhavin-qryptal** [comment]
[2102.json](https://raw.githubusercontent.com/eu-digital-green-certificates/dgc-testdata/main/ES/2DCode/raw/2102.json) seems to be using certificate which valid for clientAuth and emailProtection. Based on that it would be considered as invalid for signing HCERT - Type : Testing. Reference: https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v1_en.pdf (Appendix A - Trust management - Section A.4 Extended key Usage Identifiers)

**Comment by bhavin-qryptal** [comment]
[2103.json](https://raw.githubusercontent.com/eu-digital-green-certificates/dgc-testdata/main/ES/2DCode/raw/2103.json) : VALIDATIONCLOCK value is not in ISO8601 format as per https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/README.md

**Comment by bhavin-qryptal** [comment]
[101.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/ES/2DCode/raw/101.json)
[102.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/ES/2DCode/raw/102.json)
[103.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/ES/2DCode/raw/103.json)

Cose Message header populated with incorrect value of KID. 

Reference: https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v1_en.pdf - Appendix A - Trust management -- A.1 The Key Identifier (kids)

@Santivicen, Please have a look.

**Comment by bhavin-qryptal** [comment]
References:
[/ES/2DCode/raw/401.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/ES/2DCode/raw/401.json)
[/ES/2DCode/raw/402.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/ES/2DCode/raw/402.json)
[/ES/2DCode/raw/403.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/ES/2DCode/raw/403.json)

RE: [DGC Signing Certificate - DSC].signature_algorithm_oid

DGC Signing Certificates - DSCs are tagged with Certificate Algorithm: RSA_WITH_SHA256, However Key used is for ECDSA_WITH_SHA256. These certificates should have been tagged with ECDSA_WITH_SHA256 instead.

@Santivicen, @SchulzeStTSI, Please have a look.

**Comment by bhavin-qryptal** [comment]
[/ES/2DCode/raw/1203.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/ES/2DCode/raw/1203.json)
Getting error while try to decode COSE / CBOR payload. 
TypeError: payload should be of type 'bytes' not <class 'int'>

@Santivicen, @SchulzeStTSI, Please have a look.

**Comment by bhavin-qryptal** [comment]
[2103.json](https://raw.githubusercontent.com/eu-digital-green-certificates/dgc-testdata/main/ES/2DCode/raw/2103.json) : 

Content of the CBOR Payload does not match with JSON. 

![image](https://user-images.githubusercontent.com/84303320/118785707-b0d7d380-b8c3-11eb-832e-aff9bcd4dee6.png)

**Comment by bhavin-qryptal** [comment]
New commit has introduced few more failures. e.g. /ES/2DCode/raw/1201.json and /ES/2DCode/raw/1202.json

**Comment by dslmeinte** [comment]
I see 2001 and 2002 in the same dir. not parsing as JSON.

**Comment by dslmeinte** [comment]
2001 and 2002 have line breaks in the string value of `//TESTCTX/CERTIFICATE`.
1201 and 1202 have "COVID" as disease target, instead of the value set ID "840539006".

**Comment by bhavin-qryptal** [comment]
@SchulzeStTSI and @daniel-eder , This could be closed as latest tests for ES are good.
