### ISSUE TITLE
ES: Publickey validates against CSCA in verify service but doesn't appear on the list/doesn't get sent.

### ISSUE THREAD

**Issue by Mark-Selezenev** [eu-digital-green-certificates/dgc-testdata#323]
## Issue Description

It seems several countries are experiencing this right now that the ES publickey is in the ACC(acceptance) backend but countries can't see it including Estonia. I checked the logs and they do validate against their CSCA but it doesn't get put on the list or gets transmitted to the App or other implementations.

We are currenctly using the Java version of the verify service.

## Proposed Solution

Currently no idea, under investigation. But countries who have this problem should contribute.

**Comment by Mark-Selezenev** [comment]
Currently the publickey verified against CSCA but it doesn't get published on the list and is not distributed to the app (tried with android)

07:24:02.216  INFO 7 --- [   scheduling-1] e.e.e.d.g.c.DgcGatewayDownloadConnector  : Got Response from DGCG, Downloaded Certificates: 78

2021-06-11 07:24:02.217  INFO 7 --- [   scheduling-1] e.e.e.d.g.c.DgcGatewayDownloadConnector  : KID: B4BbJQx1lYQ=   TYPE: DSC   COUNTRY: ES

2021-06-11 07:24:05.668  INFO 7 --- [   scheduling-1] e.e.e.d.g.c.DgcGatewayDownloadConnector  : Checking cert with keyId: B4BbJQx1lYQ= against CSCA certs

2021-06-11 07:24:05.771  INFO 7 --- [   scheduling-1] e.e.e.d.g.c.DgcGatewayDownloadConnector  : Is key B4BbJQx1lYQ= verified against ca CN=EADTrust ECC 256 SubCA For Qualified Certificates 2019,O=European Agency of Digital Trust\, S.L.,C=ES,organizationIdentifier=VATES-B85626240,OU=Legal Person: true

Total  list as of right now: 

["+/bbaA9m0j0=","+3CK4II5kAg=","+Z3fx3xOKAQ=","0J/NOaUzCAg=","1vxpTLgc6ws=","2c6RCwOmTGI=","428FOlUxNRM=","67BzmdT5oYo=","6EjzyhNlGDQ=","6ek0DM8iSCs=","6jqyJk80bUU=","7/MOPvQI+WY=","727mZUPbpyc=","7JQ83GRvK3A=","9YMMwrfDdoo=","Ayod4P+EpW8=","BkMNTz/RKb8=","CFUoOhVtOgo=","CtDYk/6d0xw=","DEsVUSvpFAE=","DhspllZjSVY=","GO0rf1TneQQ=","GZ2cfMLwyK8=","H6KcgU3y0DY=","JLxre3vSwyg=","Jj+9Dw7DUVU=","KFP4Rwxlab8=","Ks/eWTAFo+I=","Ld1KH5MrFsY=","MI7hF0OCF8Y=","NJpCsMLQco4=","OTAXaM3aBRM=","Ol12Ruv8LLo=","Rl7ZUeTLAC4=","STPDGKKF4N8=","TfwLMHDXIws=","Tn6X6w0+iBM=","U5vvB3k2Cj4=","Uy2dYAJ4Rdw=","VjUQ+HzmZm0=","X3SRAZXFzss=","YTA6V2K8xQY=","bIwe3F4lAk4=","cKqkRgtW0Xw=","coWnRsJwd/s=","dAacIEGMNcE=","dsXHUWEsRfA=","eZx0UBq8T1E=","f1sfUVIx8CA=","f4ialzEsfzU=","ffE6u4r3Db0=","gklWpqtW+Tg=","gtsQTR82V6w=","hyJmFP5BVx8=","jrxzCm2qFug=","kwL2uX0ViAA=","l3DTTvY1/h0=","lHHRhMo9GWg=","lrXFYdYTLMY=","m6so0I2uIyw=","mRxapyixSJ0=","mamG6Tt5Jl8=","mkooSvJQkZ0=","nSdp31pPUvQ=","onphe00laog=","pXjP4Y6sns4=","snqSuA/dvgk=","u5Tohz8Qb+w=","uE7ViYTSegg=","uxvl+dsyrBw=","wGR6OwOYF4k=","wTHYuP2pg1k=","xZ7EcIR8I4Y=","xZUU+IopoVk=","y3g27v8r51I=","9cWXDDA52FQ=","xKOXcpzMVb0="]

**Comment by Mark-Selezenev** [comment]
Our developers also said that the verifier also checks with UPLOAD certificate which the verify service can't find for this kid. We can skip this check but is it allright?

**Comment by loujensen-dk** [comment]
Hi Mark,

We've done a quick query to the repository and our key appears in the EU repository (see imaged attached). 
Could it be that we're uploading the certificate wrong and the disable-upload-certificate-check fails? 

I think it would be helpful to raise this issue in the next QA session, as other countries have reported that the signer key is missing. 
![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/84727680/121722985-45f67280-cae6-11eb-8f1e-b297bcfbd1d5.png)

**Comment by SchulzeStTSI** [comment]
Can you please check if you use the latest dgc-lib?

**Comment by carballAcc** [comment]
From the Spain team. The Acceptance publickey has been re-uploaded with an updated upload certificate. We have also updated the version of the library. Can you test if you can see the Spanish publickey now?

**Comment by Mark-Selezenev** [comment]
> From the Spain team. The Acceptance publickey has been re-uploaded with an updated upload certificate. We have also updated the version of the library. Can you test if you can see the Spanish publickey now?

Yeah it is working now. Closing.
