### ISSUE TITLE
test data does not pass validation of TAC Verif

### ISSUE THREAD

**Issue by azzouzze** [eu-digital-green-certificates/dgc-testdata#383]
need your help validating test data on Verif.
why are all QR code not passing TAC Verif, frence app ?

thank you

**Comment by daniel-eder** [comment]
The testdata in this repository may be signed with keys from the test environment, the productive apps may fail on such testdata.
If you head over to https://github.com/eu-digital-green-certificates/dcc-quality-assurance you can find testdata that is either allready production, or soon to be in production (may vary from qr code to qr code)
