### ISSUE TITLE
BE: can't inflate test data

### ISSUE THREAD

**Issue by simonh1000** [eu-digital-green-certificates/dgc-testdata#388]
**Affected Country**: BE

## Issue Description

I am able to decode the data in my own QR Code (covidsafe app), but while the prefix data [here](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/BE/2DCode/raw/1.json#L29) can be base45 decoded, it cannot be Inflated, nor can it be converted into cbor.

**Comment by PeterEbraert** [comment]
Hello there,

Don't understand what the problem is... Can you get into contact with me on slack to elaborate on this?

Thanks,

Peter Ebraert (team BE)

**Comment by simonh1000** [comment]
Hi, I can't find a way to join Slack, so let me try to be clearer. 

I'm trying to get the data from the QR Code.

My own certificate has content of `HC1:...`.  If I pass it through a multi stage process of 
- drop "HC1:" from front
- decode base45
- Gzip.inflate
- decode the binary cbor data

I get the expected json.

But with the [test data](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/BE/2DCode/raw/1.json#L29), this pipeline fails. The base45 decode reports a success but the inflate fails, and just skipping the inflate is not a workaround.

So I am wondering whether the test data has constructed using some other sequence?

**Comment by krlnokrl** [comment]
Hello,

I believe there might be an issue with your implementation. Using the [python trivial implementation](https://github.com/ehn-dcc-development/ehn-sign-verify-python-trivial/blob/main/hc1_verify.py) the testdata decompresses fine.
I have tested the string with a few implementations of zlib and they all pass.

The specification requires the use of zlib compression format. Gzip is not the same as Zlib.

|         | zlib           | Gzip |
|---------|----------------|------|
| Headers | 0x78 | 1F8B |

**Comment by simonh1000** [comment]
My mistake - it is inflateZLib that I am using, so that's not the error. 

I'm doing this in Elm using https://package.elm-lang.org/packages/folkertdev/elm-tiny-inflate/latest/Inflate so there could be a bug there i guess

I'll play around some more

**Comment by daniel-eder** [comment]
@simonh1000 to join slack visit https://github.com/eu-digital-green-certificates/dgc-overview, the table contains an invite link

**Comment by simonh1000** [comment]
It's somewhere in my own base45 decoding - apologies
