### ISSUE TITLE
Create your own certificate? Is this possible

### ISSUE THREAD

**Issue by wege2003** [eu-digital-green-certificates/dgc-testdata#403]
Hello there!
i have one question about the generation of certificates. 

## Issue Description
Is it possible to create your own certificate with a normal qr-encoder? I am scared if this is possible because then everybody can fake their covid 19 certificates? Do you know if its possible or not?

## Proposed Solution
If this is possible i hope they will fix it, otherwise this would be scarry

**Comment by daniel-eder** [comment]
Hi @wege2003 

This is an important topic, and it was considered when the system was designed. 
As a result, this is not possible. DCCs use a digital signature to verify the certificate was created by a valid authority. That means if someone without an accepted private key creates and signs a certificate, it will be recognized as invalid. Similarly, if someone would modify a valid and signed certificate the verification apps would see that the content and signature no longer match.

If you are interested in detailed information, visit our [overview page](https://github.com/eu-digital-green-certificates/dgc-overview), where you can find links to the specification and other technical documents.
