### ISSUE TITLE
Not allowed characters in UVCI for DK entries

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#42]
@jvitrifork Creating an issue since we don't have a better way of communicating.

The format of the UVCI (`ci`) used in DK files contains characters outside of the allowed character set. See https://github.com/ehn-digital-green-development/ehn-dgc-schema/wiki/FAQ.

**Comment by jvitrifork** [comment]
An issue is fine.

Yep - that's a bug

**Comment by jvitrifork** [comment]
ok - well, thanks for the heads up

**Comment by jvitrifork** [comment]
Fix comming up

**Comment by daniel-eder** [comment]
Fixed in #49 - thank you @jvitrifork
