### ISSUE TITLE
Who would help me and teach me how to create a Covid certificate (I will pay)

### ISSUE THREAD

**Issue by zielony666** [eu-digital-green-certificates/dgc-testdata#436]
hey i'm new here. I understand a lot about it, what's going on and how, but I can't connect it all.
if someone invested some time to explain, I would be grateful.
End of course I will pay for this help.
I speak 3 languages: German, Polish and English, but a bit weaker

**Comment by zielony666** [comment]
@SchulzeStTSI can we talk on Telegram?

**Comment by daniel-eder** [comment]
@zielony666 to find a community of people working with DCCs you might want to join the slack channel linked in https://github.com/eu-digital-green-certificates/dgc-overview#where-can-i-find-

**Comment by DAWWAL** [comment]
I need help creating my qr code

**Comment by beermeer** [comment]
Hey @zielony666 
Also a German here and I speak english and a little big polski. Ich würde mich gerne anschließen. Telegram?

**Comment by beermeer** [comment]
@DAWWAL me also, did you find out something?

**Comment by Pujski** [comment]
@beermeer hast du was herausgefunden?

**Comment by beermeer** [comment]
> @beermeer hast du was herausgefunden?

Nein, leider nicht. Und du? :/

**Comment by DAWWAL** [comment]
??

śr., 8 gru 2021, 22:39 użytkownik beermeer ***@***.***>
napisał:

**Comment by Pujski** [comment]
Sorry. Just replied, if he found some help by that.

**Comment by ZEcaptn** [comment]
Hello Guys, can someone give me some help.
I'm on telegram and i would pay for the help

**Comment by dannyhax0** [comment]
I'm willing to pay as well.
my email is: ᴅᴀɴɴʏʜᴀx𝟶‎@‎ɢᴍᴀ‎ɪʟ.ᴄᴏᴍ

let me know.

**Comment by AlexanderZwo** [comment]
@dannyhax0, @zielony666, @ZEcaptn, @DAWWAL, @beermeer 
Please, send your request to the Ministry of Health in your country, which is coordinating your country's connection to the EU DCC Ecosystem.
Bitte richten sie Ihre Anfrage an das Gesundheitsministerium Ihres Landes, welches für Ihr Land die Anbindung Ihres Landes an das EU DCC Ecosystems koordiniert.
