### ISSUE TITLE
How to create valid Certificates?

### ISSUE THREAD

**Issue by dannyhax0** [eu-digital-green-certificates/dgc-testdata#444]
Hello everyone.
So I'm trying to dive deeper on these Certificates.

Can anyone give me an help on how to create a valid certificate and explaining how it works?

I'm willing to pay.

my email is: **ᴅᴀɴɴʏʜᴀx𝟶‎@‎ɢᴍᴀ‎ɪʟ.ᴄᴏᴍ** 

Let me know, I reply asap.

**Comment by AlexanderZwo** [comment]
@dannyhax0 
Please, send your request to the Ministry of Health in your country, which is coordinating your country's connection to the EU DCC Ecosystem.
