### ISSUE TITLE
IS test file parsing

### ISSUE THREAD

**Issue by asitdm** [eu-digital-green-certificates/dgc-testdata#47]
Hi @gunnarif,

it seems that the version in your files is a String while it should be an Int according to the scheme definition (see below). This results in a parsing exception on stricter JSON parsers. Could you by chance update your files?

```
   "TESTCTX":{
       "VERSION": **integer**,
```

**Comment by gunnarif** [comment]
hi @asitdm
sorry, fixed when the pull request gets accepted
