### ISSUE TITLE
Why is private key needed?

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#5]
From the readme:

> **JWK Content**
>
> The key pair to sign and validate the data structures. This is defined as x5c datastructure which contains the complete key pair.

Is doesn't make sense to pass in the private key. The certificate/public key should be sufficient.

**Comment by martin-lindstrom** [comment]
Step 3 of the test instructions say:

> Sign with the JWK and compare the result to the COSE content.

Clearly you want a signature validation to be performed here? No a signature operation with a private key.

**Comment by SchulzeStTSI** [comment]
Okay, removed in commit : https://github.com/eu-digital-green-certificates/dgc-testdata/pull/4/commits/35c68d03c36503a52b86db003921add6c42eb1de
