### ISSUE TITLE
Help needed how to create the test data

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgc-testdata#51]
Hi All, 

I have the issuer and validator services up and running, I also have the issuer web installed, and working.
I am able to produce the QR codes using these template applications.

How are you creating the test data, with the info required as per the json schema?
ie: How are you generating the payload below?

```
{
   "JSON": **JSON OBJECT**,
   "CBOR": **CBOR (hex encoded)**,
   "COSE": **COSE (hex encoded)**,
   "COMPRESSED": **COMPRESSED (hex encoded)**,
   "BASE45": **BASE45 Encoded compressed COSE**,
   "PREFIX": **BASE45 Encoded compressed COSE with Prefix HC(x):**,
   "2DCODE": **BASE64 Encoded PNG**,
   "TESTCTX":{
       "VERSION": **integer**,
       "SCHEMA": **string (USED SCHEMA, semver)**,
       "CERTIFICATE": **BASE64** ,
       "VALIDATIONCLOCK": **Timestamp**, (https://docs.jsonata.org/date-time-functions ISO8601)
       "DESCRIPTION": **string**
   },
   "EXPECTEDRESULTS": {
       "EXPECTEDVALIDOBJECT": **boolean**,
       "EXPECTEDSCHEMAVALIDATION": **boolean**,
       "EXPECTEDENCODE": **boolean**,
       "EXPECTEDDECODE": **boolean**,
       "EXPECTEDVERIFY": **boolean**,
       "EXPECTEDCOMPRESSION": **boolean**,
       "EXPECTEDKEYUSAGE": **boolean**,
       "EXPECTEDUNPREFIX": **boolean**,
       "EXPECTEDVALIDJSON": **boolean**,
       "EXPECTEDB45DECODE": **boolean**,
       "EXPECTEDPICTUREDECODE": **boolean**,
       "EXPECTEDEXPIRATIONCHECK": **boolean**,
    }
}
```

**Comment by DragoMlakar** [comment]
@psavva 
You may find this useful, but not sure if this is official way to do it.
https://github.com/ehn-digital-green-development/dgc-java/blob/main/create-validate/src/test/java/se/digg/dgc/interop/CreateTestDataTest.java

**Comment by martin-lindstrom** [comment]
@DragoMlakar @psavva No, it's not official in any way. And using this code (my code) is only relevant if you use the dgc-java library for your DGC issuance. The thing with this repo is that we test each others QR-codes that will be used in production.

**Comment by psavva** [comment]
Thank you all for your comments.
We have created the test data using the web issuing frontend and spooling out some logs of the data we need.  Constructed the needed examples based on the tests we had run...
