### ISSUE TITLE
Please elaborate on file structure

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#6]
It is a bit unclear on how countries should supply their test files.

In my mind each country has a directory, in which each test file reside. For example:

- `/SE/README.md` - Describes the Swedish test files.
- `/SE/1.json` - First test file.
- `/SE/2.json` - ....

**Comment by SchulzeStTSI** [comment]
The current structure would be 
/SE/Readme.md
/SE/2DCode/raw/1.json
