### ISSUE TITLE
Test files from Italy are not correct

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#60]
The CBOR, COSE and COMPRESSED fields are Base64-encoded. Should be hex-encoded.

@SchulzeStTSI Should be easy to spot even without tools before approving PR ;-)

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom Sorry. It's the time to setup a CI. I have already some ideas.

**Comment by daniel-eder** [comment]
Closed in #72
