### ISSUE TITLE
DoB field doesn't pass schema validation

### ISSUE THREAD

**Issue by vanton1** [eu-digital-green-certificates/dgc-testdata#61]
@jvitrifork [Denmark's 7th example](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/DK/2DCode/raw/7.json) has dob with value 1899-04-20. Is this on purpose? Because it doesn't pass schema validation We use this schema [here](https://github.com/eu-digital-green-certificates/ehn-dgc-schema/blob/main/DGC.schema.json)

**Comment by jkiddo** [comment]
@vanton1 you are correct. That example violatest the schema

**Comment by jvitrifork** [comment]
Should be fixed with https://github.com/eu-digital-green-certificates/dgc-testdata/pull/103

**Comment by vanton1** [comment]
Yes it seems the three examples in your PR work fine

**Comment by jvitrifork** [comment]
@SchulzeStTSI - this issue should be closed
