### ISSUE TITLE
DK: Schema violation on 5.json

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#67]
The DK 5.json file states `EXPECTEDSCHEMAVALIDATION = true` meaning that schema validation should succeed, but empty arrays in `t` and `r` makes schema validation fail.

**Comment by jvitrifork** [comment]
Fixed with https://github.com/eu-digital-green-certificates/dgc-testdata/pull/103

**Comment by jvitrifork** [comment]
This issue should be closed @SchulzeStTSI
