### ISSUE TITLE
Suggestion: Replace jwk with Base64-encoded certificate

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#7]
Instead of placing the certificate in a JWK (where nothing else is represented), we might as well just represent the signer certificate as a Base64-encoded string. That's simpler and we don't have to create incomplete JWK-objects.

**Comment by SchulzeStTSI** [comment]
Done in https://github.com/eu-digital-green-certificates/dgc-testdata/pull/4/commits/67c4ada5309dc8d910a2ab9dc550de4b0b8343c9
