### ISSUE TITLE
HR: Empty strings in optional fields

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#70]
@kristinaleko In file HR 2.json, the optional fields `ma` and `nm` are present and hold empty strings. The correct is to not include these fields if they haven't got a value. Including an empty string for `ma` leads to validation errors when checking against allowed value-set.

**Comment by kristinaleko** [comment]
@martin-lindstrom @daniel-eder also for testing and closure :)
