### ISSUE TITLE
COSE input missing for EXPECTEDVERIFY spec in common/2DCode/raw/CBO2.json

### ISSUE THREAD

**Issue by jeroentrappers** [eu-digital-green-certificates/dgc-testdata#74]
@nodh 

in Common CBO2 this is the test spec:
"EXPECTEDVERIFY": false

EXPECTEDVERIFY: Data from input in COSE can be cryptographically verified, 
with signer's certificate from TESTCTX.CERTIFICATE

But the test spec file does not contain a COSE input.

**Comment by nodh** [comment]
Thanks for spotting that, I'm gonna fix that

**Comment by bhavin-qryptal** [comment]
Reference: https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/README.md

Question 1: Which of the following interpretations are correct? 

1.
EXPECTEDDECODE: Data from input in CBOR can be decoded, and the contents match input from JSON
OR
EXPECTEDDECODE: Extract the CBOR content and validate the CBOR content against the RAW CBOR content field.

2.
EXPECTEDVALIDJSON: Data from input (i.e. 2DCODE or PREFIX) can be decoded (whole chain), and the contents match input from JSON
OR
EXPECTEDVALIDJSON: Transform CBOR into JSON and validate against the RAW JSON content.

Question 2:
Should JSON payload inside of CBOR and COSE of test data contain full JSON Payload with Keys -260, 2, 4, 6 etc. See an image for illustration.
![image](https://user-images.githubusercontent.com/84303320/118791306-298d5e80-b8c9-11eb-9e31-58b9d2c90d36.png)
OR 
Payload inside Key -260? See another image for illustration.
![image](https://user-images.githubusercontent.com/84303320/118791390-3f9b1f00-b8c9-11eb-9f63-61ee07cf893d.png)

I believe, it should be earlier. However examples under common folder does not follow that. e.g. 
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/common/2DCode/raw/CO1.json

**Comment by nodh** [comment]
> Question 1: Which of the following interpretations are correct?
> 
> 
> EXPECTEDDECODE: Data from input in CBOR can be decoded, and the contents match input from JSON
> OR
> EXPECTEDDECODE: Extract the CBOR content and validate the CBOR content against the RAW CBOR content field.
> 
> 
> EXPECTEDVALIDJSON: Data from input (i.e. 2DCODE or PREFIX) can be decoded (whole chain), and the contents match input from JSON
> OR
> EXPECTEDVALIDJSON: Transform CBOR into JSON and validate against the RAW JSON content.

In my opinion, in both cases the first interpretation.

> Question 2:
> Should JSON payload inside of CBOR and COSE of test data contain full JSON Payload with Keys -260, 2, 4, 6 etc. See an image for illustration.
> OR
> Payload inside Key -260? See another image for illustration

`COSE` should contain the whole COSE Object, i.e. with protected header, unprotected header, payload and signature. The payload contains a `CWT` that has the keys you mentioned (i.e. issuedAt, expiration, and -260).
`CBOR` should contain the DGC only, i.e. what is wrapped in `1` in `-260` in the payload of the COSE.
This has been discussed in https://github.com/eu-digital-green-certificates/dgc-testdata/issues/18, too.
