### ISSUE TITLE
Invalid signing algorithm parameter

### ISSUE THREAD

**Issue by jeroentrappers** [eu-digital-green-certificates/dgc-testdata#75]
@nodh 

https://github.com/eu-digital-green-certificates/dgc-testdata/blob/6a13914d9531943cffa602abc58c721789325450/common/2DCode/raw/CO1.json#L36

When testing this file, I got a -37 as value for the signing algorithm.

This seems to be an unknown value voor COSE. It is not clear for me which algorithm should be used to verify this signature. 

Accoring to the spec, only 2 algorithms should be supported. The value for these is -7. 

Trying with the -7 algorithm for RSA. The signature is invalid too.

**Comment by jeroentrappers** [comment]
Same for common/2DCode/raw/CO2.json

**Comment by jeroentrappers** [comment]
see https://datatracker.ietf.org/doc/html/rfc8152#section-8.1

**Comment by asitplus-pteufl** [comment]
we noticed that RSA is not supported with many COSE-libs, but the header for RSA-PSS is correct, it is -37
RSA-PSS https://tools.ietf.org/id/draft-jones-cose-rsa-04.html

-7 is ECDSA with NIST P256 and -37 is RSA-PSS with SHA256

**Comment by asitplus-pteufl** [comment]
Better link:
https://www.iana.org/assignments/cose/cose.xhtml
go to table "COSE Algorithms" for a complete overview

**Comment by jeroentrappers** [comment]
Thank you for the feedback. I've implemented this in our decoder / verifier.
