### ISSUE TITLE
How can i verify the KID?

### ISSUE THREAD

**Issue by jeroentrappers** [eu-digital-green-certificates/dgc-testdata#76]
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/6a13914d9531943cffa602abc58c721789325450/common/2DCode/raw/CO22.json#L10

It does not seem to be present in the test spec. Is it extractable from the Certificate somehow? I've found no official spec for the kid.

**Comment by jeroentrappers** [comment]
Same question for 2DCode/raw/CO23.json. The verification is succesful with the provided certificate, both CO22.json and CO23.json.

**Comment by SchulzeStTSI** [comment]
@jeroentrappers The kid is defined as the first 8 bytes of the SHA256 hash of the certificate.

**Comment by jeroentrappers** [comment]
Thanks!
