### ISSUE TITLE
ES: Illegal transliteration and value set violations

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#81]
In **501.json**:

Transliterated names containing blanks. Illegal.

`ma` field of test entry is invalid. Violates covid-19-lab-test-manufacturer-and-name.

In **502.json**:

Transliterated names containing blanks. Illegal.

In **503.json**:

Transliterated names containing blanks. Illegal.

In **1201.json**:

`vp` field of vaccination entry is invalid. Violates sct-vaccines-covid-19.

`dn` (2) is larger that total number of doses in series `sd` (1). This doesn't make sense.

In **1202.json**:

t[0].ma="Value 'BIOSYNEX COVID-19 Ag BSS' is not allowed according to the 'covid-19-lab-test-manufacturer-and-name' value-set"

t[0]="sc (sample collection) is after dr (date of result). This doesn't make sense"

t[0].tr="Value '1240591000000102' is not allowed according to the 'covid-19-lab-result' value-set"

In **2001.json**:

t="Empty array in 't' - not allowed"

r="Empty array in 'r' - not allowed"

In **2002.json**:

v="Empty array in 'v' - not allowed"

t="Empty array in 't' - not allowed"

**Comment by Santivicen** [comment]
I have remove that invalid test and I have created a new pull request with new tests looking your comments.

**Comment by daniel-eder** [comment]
Closed in #87
