### ISSUE TITLE
HR: Use of empty strings where null should be used

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#82]
In HR 2.json:

WARNING: t[0].nm="Optional field is empty string (or blanks only) - better to set as null", 

WARNING t[0].ma="Optional field is empty string (or blanks only) - better to set as null" 

WARNING t[0].sc="DateTime represented as un-tagged string (should be tagged with 0)"

WARNING t[0].dr="DateTime represented as un-tagged string (should be tagged with 0)"

**Comment by daniel-eder** [comment]
@kristinaleko can you look into this?

**Comment by kristinaleko** [comment]
@daniel-eder @martin-lindstrom this is also for retesting uploaded.

**Comment by daniel-eder** [comment]
Passes automatic test now
