### ISSUE TITLE
IS: packaging the KID in a Tag

### ISSUE THREAD

**Issue by dirkx** [eu-digital-green-certificates/dgc-testdata#88]
@gunnarif  -- It seems that the Islandic KID is packaged in a tag:

       18(
         [
           / protected / h'a2012604c4483526eba1164a1d54' / {
               \ alg \ 1:-7 \ ECDSA 256 \, 
               **\ kid \ 4:4(
                 h'3526eba1164a1d54'
               )**
             } / , 
           / unprotected / {}, 
           / payload / h'a401624953041a60a3890b061a609a4e8b390103a101a4617681aa6263696f30312049532f41424331323334234b62636f62495362646e026264746a323032312d30312d303162697378254469726563746f72617465206f66204865616c7468206f66204963656c616e642054657374626d616d4f52472d313030303330323135626d706c45552f312f32302f313532386273640262746769383430353339303036627670674a30374258303363646f626a323030302d30312d3031636e616da462666e6b5072c3b366617261736f6e62676e70c39e6172662041c3b0205072c3b3666163666e746a50524f46415241534f4e63676e746e54484152463c41443c50524f46416376657265312e302e30', 
           / signature / h'f33ba8160454cce0b5bd39fc5c5948e9316b3bbd1a71740e2d7f7d75ffdc9750d632372c0c45c8d2d3311f12a57275da2f8ef6f0edea7276c8d6db652883ad9d'
         ]
       )
       
Is that correct/intentional =- rfc8152 seems to suggest an opaque bstring -- and the spec the first 8 bytes of the hash ?

Or am I missing something subtle ?

**Comment by gunnarif** [comment]
@dirkx 
It's a bug on my part.
Fixed in next pull request.

**Comment by SchulzeStTSI** [comment]
@gunnarif can this issue be closed?

**Comment by gunnarif** [comment]
Maybe if @dirkx can confirm, it would be appreciated

**Comment by dirkx** [comment]
Looking lovely and passes all our baseline sign/etc checks.

````
dirkx@cheesegrater ehn-sign-verify-python-trivial % sh test-dgc-testdata.sh IS
dgc-testdata/IS/2DCode/raw/1.json
Issuer              : IS
Experation time     : 1621619201
Issued At           : 1621014401
Health payload      : {"v": [{"ci": "01 IS/ABC1234#K", "co": "IS", "dn": 2, "dt": "2021-01-01", "is": "Directorate of Health of Iceland Test", "ma": "ORG-100030215", "mp": "EU/1/20/1528", "sd": 2, "tg": "840539006", "vp": "J07BX03"}], "dob": "2000-01-01", "nam": {"fn": "Pr\u00f3farason", "gn": "\u00dearf A\u00f0 Pr\u00f3fa", "fnt": "PROFARASON", "gnt": "THARF<AD<PROFA"}, "ver": "1.0.0"}
dgc-testdata/IS/2DCode/raw/2.json
Issuer              : IS
Experation time     : 1621619205
Issued At           : 1621014405
Health payload      : {"t": [{"ci": "01 IS/ABC4556#8", "co": "IS", "dr": "2021-05-14T17:46:45Z", "is": "Directorate of Health of Iceland Test", "ma": "1304", "sc": "2021-05-14T13:46:45Z", "tc": "Department of ClinicalMicrobiology,Landspitali", "tg": "840539006", "tr": "260415000", "tt": "LP6464-4"}], "dob": "2000-01-01", "nam": {"fn": "Mj\u00f6ggottson", "gn": "Ekki V\u00edrus", "fnt": "MJOEGGOTTSON", "gnt": "EKKI<VIRUS"}, "ver": "1.0.0"}
```
