### ISSUE TITLE
IT: 1 field contains  "Ministero della Salute" - should be "IT"

### ISSUE THREAD

**Issue by dirkx** [eu-digital-green-certificates/dgc-testdata#89]
@alfo1995 - It appears that in the JSON we get:

       {4: 1636483169, 
      6: 1620927569,
       1: "_**Ministero della Salute**_", 
     -260: {....
     
 for the payload.  I think the spec (https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md
) suggests that this should be just the country:
 
*  Payload
**   Issuer (iss, claim key 1, optional, ISO 3166-1 alpha-2 of issuer)
** ....

So I guess for italy that should be:

       {4: 1636483169, 
      6: 1620927569,
       1: "IT", 
     -260: {....

With kind regards,

**Comment by alfo1995** [comment]
thanks @dirkx  we fixed it here #111
