### ISSUE TITLE
EXPTECTEDEXPIRED -> EXPECTEDEXPIRATIONCHECK

### ISSUE THREAD

**Issue by martin-lindstrom** [eu-digital-green-certificates/dgc-testdata#9]
All variables in the `EXPECTEDRESULTS` are true for a successful test except for `EXPTECTEDEXPIRED` that needs to be `false` (meaning, DGC is not expected to be expired). It would make more sense to rename this so that it also could be set to `true` for a successful test. 

`EXPECTEDEXPIRATIONCHECK`?

**Comment by SchulzeStTSI** [comment]
Fixed in this request. https://github.com/eu-digital-green-certificates/dgc-testdata/pull/10

**Comment by SchulzeStTSI** [comment]
Pull request merged.
