### ISSUE TITLE
ES: Linebreaks in JSON of example 201, 202, 203

### ISSUE THREAD

**Issue by dirkx** [eu-digital-green-certificates/dgc-testdata#90]
@TKlauenberg : The base64 for the CERTIFICATE in /ES/2DCode/raw/201.json  has \n by accident. A lot of parsers will error out with:

       parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 48, column 33

**Comment by jeroentrappers** [comment]
Related to #32

**Comment by dirkx** [comment]
Closed - duplicate of #32
