### ISSUE TITLE
ES: key IDs not abbreviated to 8 byts

### ISSUE THREAD

**Issue by dirkx** [eu-digital-green-certificates/dgc-testdata#91]
@TKlauenberg could it be that the key IDs are somewhow not reduced to the 8 bytes as per section A.1 of https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md ??

I am getting an unknown on dgc-testdata/ES/2DCode/raw/103.json:

      Exception: KeyID is unknown (expected b'07805b250c759584', got b'3736377a523661474c503564475a71656663506d77436e64573536556f33646f6477326176427376797938') -- cannot verify.

**Comment by lab-incert** [comment]
I confirm we got the same issue.

**Comment by bhavin-qryptal** [comment]
Getting same issue. 

101.json , 102.json and 103.json
Expected :b'\x07\x80[%\x0cu\x95\x84'
Actual   :b'767zR6aGLP5dGZqefcPmwCndW56Uo3dodw2avBsvyy8'

**Comment by daniel-eder** [comment]
@Santivicen can you take a look at this?

**Comment by Santivicen** [comment]
Hi, We have submit this test in our last pull request, could you take a look, please?

**Comment by daniel-eder** [comment]
Files 101, 102, 103 are now valid as per https://github.com/eu-digital-green-certificates/dgc-testdata/actions/runs/878871168 (see xpasses)
