### ISSUE TITLE
SI: c2tnb191v1 curve in dgc-testdata/SI/2DCode/raw/1.json and 2.json

### ISSUE THREAD

**Issue by dirkx** [eu-digital-green-certificates/dgc-testdata#94]
@DragoMlakar: It appears as if the DCS for this json is not a NIST P-256 but a 191 bit c2tnb191v1 curve ?

Could that be ?

      Certificate:
          Data:
              Version: 3 (0x2)
              Serial Number: 1620739844 (0x609a8704)
              Signature Algorithm: ecdsa-with-SHA256
              Issuer: C = SI, L = Ljubljana, O = SETCCE, OU = dev, CN = signer
              Validity
                  Not Before: May 11 13:30:44 2021 GMT
                  Not After : May 11 13:30:44 2022 GMT
              Subject: C = SI, L = Ljubljana, O = SETCCE, OU = dev, CN = signer
              Subject Public Key Info:
                  Public Key Algorithm: id-ecPublicKey
                      Public-Key: (191 bit)
                      pub:
                          04:01:62:23:e7:6c:68:47:c8:4c:d1:17:9c:c2:94:
                          f2:a7:7b:a7:cf:61:99:01:a2:75:7a:55:e4:8c:06:
                          5c:cb:f7:c4:49:9f:e2:55:84:d4:be:d5:4f:61:90:
                          0f:f7:60:34
                      ASN1 OID: c2tnb191v1
          Signature Algorithm: ecdsa-with-SHA256
               30:34:02:18:06:38:77:eb:fb:d4:d3:10:ad:55:20:f4:57:08:
               ce:b3:6d:a9:91:cc:a0:ea:7e:6f:02:18:13:36:ae:60:d1:c6:
               cb:35:5c:c6:1c:b7:66:64:57:a1:34:9b:84:90:ae:de:6f:2e
      -----BEGIN CERTIFICATE-----
      MIIBcTCCASigAwIBAgIEYJqHBDAKBggqhkjOPQQDAjBRMQswCQYDVQQGEwJTSTES
      MBAGA1UEBwwJTGp1YmxqYW5hMQ8wDQYDVQQKDAZTRVRDQ0UxDDAKBgNVBAsMA2Rl
      djEPMA0GA1UEAwwGc2lnbmVyMB4XDTIxMDUxMTEzMzA0NFoXDTIyMDUxMTEzMzA0
      NFowUTELMAkGA1UEBhMCU0kxEjAQBgNVBAcMCUxqdWJsamFuYTEPMA0GA1UECgwG
      U0VUQ0NFMQwwCgYDVQQLDANkZXYxDzANBgNVBAMMBnNpZ25lcjBJMBMGByqGSM49
      AgEGCCqGSM49AwAFAzIABAFiI+dsaEfITNEXnMKU8qd7p89hmQGidXpV5IwGXMv3
      xEmf4lWE1L7VT2GQD/dgNDAKBggqhkjOPQQDAgM3ADA0AhgGOHfr+9TTEK1VIPRX
      CM6zbamRzKDqfm8CGBM2rmDRxss1XMYct2ZkV6E0m4SQrt5vLg==
      -----END CERTIFICATE-----

**Comment by jeroentrappers** [comment]
Related to #77 and #79

**Comment by dirkx** [comment]
closing - duplicate of #77 and #79
