### ISSUE TITLE
HR/Croatia - non ISO country code in Issuer field ?

### ISSUE THREAD

**Issue by dirkx** [eu-digital-green-certificates/dgc-testdata#95]
In the file:
    dgc-testdata/HR/2DCode/raw/1.json

The issuer seems to be set to ```Ministry of Health, Croatia``` rather than to an 2 char ISO country code (as per section 3.3.1:

* Payload
** Issuer (iss, claim key 1, optional, ISO 3166-1 alpha-2 of issuer)

of https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md). Is that intentional ?

**Comment by daniel-eder** [comment]
@kristinaleko can you weigh in on this?

**Comment by kristinaleko** [comment]
@daniel-eder @dirkx new qr codes are uploaded, can you retest if this can be closed.

**Comment by dirkx** [comment]
Looks good !
```

qrdecode ~/Downloads/1.png | ./hc1_verify.py -i
Issued At           : 1621427453
Experation time     : 1781740799
Issuer              : HR
Health payload      : 
{
  "r": [
    {
      "ci": "urn:uvci:01:HR:MZ0000000314",
      "co": "HR",
      "df": "2020-12-15",
      "du": "2021-06-13",
      "fr": "2020-12-01",
      "is": "Ministry of Health",
      "tg": "840539006"
    }
  ],
  "dob": "2000-01-01",
  "nam": {
    "fn": "FERNÁNDEZ",
    "gn": "RAMÓN",
    "fnt": "FERNANDEZ",
    "gnt": "RAMON"
  },
  "ver": "1.0.0"
}
``

**Comment by kristinaleko** [comment]
@dirkx thank you dirk :)
